INSERT INTO [dbo].[SERVICE_ACCOUNT]
    ([ACCOUNT]
    ,[DESCRIPTION]
    ,[INTERNAL_COMPANY_ID]
    ,[DIRECTION]
    ,[CREATE_USER]
    ,[CREATE_TIMESTAMP]
    ,[UPDATE_USER]
    ,[UPDATE_TIMESTAMP])
select distinct
	SERVICE_ACCOUNT,
	SERVICE_ACCOUNT,
	tf.INTERNAL_COMPANY_ID,
	1,
	'sys170117',
	getdate(),
	'sys170117',
	getdate()
from TARIFF t join TARIFF_FILE tf on t.TARIFF_FILE_ID = tf.TARIFF_FILE_ID
	join TARIFF_INFO ti on t.TARIFF_INFO_ID = ti.TARIFF_INFO_ID
where SERVICE_ACCOUNT not in (select ACCOUNT from SERVICE_ACCOUNT where INTERNAL_COMPANY_ID = tf.INTERNAL_COMPANY_ID)