select rpt.RPT_ID, rpt.[TYPE], rpt.TRANSPORT_ID as TR_ID, rpt.INVENTORY_STATUS as I_ST,
	case rpt.INVENTORY_STATUS when 0 then 'Open' when 1 then 'Pending' when 2 then 'Done' end as I_STATUS,
	rpt.STOCK_INVENTORY_REQUEST_ID as SIR_ID, rpt.UPDATE_TIMESTAMP,
	r.ORDER_ITEM_ID as OI_ID, r.[STATUS] as ST,
	case r.[STATUS] when 0 then 'Open' when 1 then 'Processing' when 2 then 'Completed' when 3 then 'Closed' end as [STATUS],
	si.STOCK_INFO_ID,
	si.STOCK_INFO_CONFIG_ID, sic._KEY_, siq.QUANTITY as BASE, siqSt.QUANTITY as STORAGE,
	c.[DATE] as CTXT_DATE, r.CREATE_USER, r.CREATE_TIMESTAMP, r.UPDATE_USER, r.UPDATE_TIMESTAMP
from (
select LOADING_OPERATION_REPORT_ID as RPT_ID, 'Loading' as [TYPE], REPORTED_ID, TRANSPORT_ID, INVENTORY_STATUS, STOCK_INVENTORY_REQUEST_ID, UPDATE_TIMESTAMP from LOADING_OPERATION_REPORT lor
union select DISCHARGING_OPERATION_REPORT_ID, 'Discharging', REPORTED_ID, TRANSPORT_ID, INVENTORY_STATUS, STOCK_INVENTORY_REQUEST_ID, UPDATE_TIMESTAMP from DISCHARGING_OPERATION_REPORT dor
union select VAS_OPERATION_REPORT_ID, 'VAS', vif.STOCK_INFO_ID, '', INVENTORY_STATUS, STOCK_INVENTORY_REQUEST_ID, UPDATE_TIMESTAMP from VAS_OPERATION_REPORT vor join VAS_ITEM_FROM vif on vif.VAS_ITEM_ID = vor.REPORTED_ID
union select STOCK_CHANGE_OPERATION_REPORT_ID, 'Stock-change', sci.FROM_ID, '', INVENTORY_STATUS, STOCK_INVENTORY_REQUEST_ID, scor.UPDATE_TIMESTAMP from STOCK_CHANGE_OPERATION_REPORT scor join STOCK_CHANGE_ITEM sci on scor.REPORTED_ID = sci.STOCK_CHANGE_ITEM_ID
) as rpt
join OPERATION_REPORT r on r.OPERATION_REPORT_ID = rpt.RPT_ID
join OPERATION_CONTEXT c on r.CONTEXT_ID = c.OPERATION_CONTEXT_ID
join STOCK_INFO si on si.STOCK_INFO_ID = rpt.REPORTED_ID
join STOCK_INFO_CONFIG sic on sic.STOCK_INFO_CONFIG_ID = si.STOCK_INFO_CONFIG_ID
join STOCK_INFO_QUANTITY siq on si.BASE_QUANTITY_ID = siq.STOCK_INFO_QUANTITY_ID
left join STOCK_INFO_QUANTITY siqSt on si.STORAGE_QUANTITY_ID = siqSt.STOCK_INFO_QUANTITY_ID
where rpt.RPT_ID = 499197

--update LOADING_OPERATION_REPORT set INVENTORY_STATUS = INVENTORY_STATUS+1, STOCK_INVENTORY_REQUEST_ID=404538 where LOADING_OPERATION_REPORT_ID = 491593
--update LOADING_OPERATION_REPORT set INVENTORY_STATUS = 0 where LOADING_OPERATION_REPORT_ID = 492406
--update OPERATION_REPORT set STATUS = 0 where OPERATION_REPORT_ID = 492406

select s.*, b_siq.QUANTITY, sic._KEY_
from STOCK s
inner join STOCK_INFO si on si.STOCK_INFO_ID = s.STOCK_INFO_ID
inner join STOCK_INFO_CONFIG sic on sic.STOCK_INFO_CONFIG_ID = si.STOCK_INFO_CONFIG_ID
inner join STOCK_INFO_QUANTITY b_siq on si.BASE_QUANTITY_ID = b_siq.STOCK_INFO_QUANTITY_ID
--join STOCK_INFO_SID sis on sis.STOCK_INFO_CONFIG_ID = sic.STOCK_INFO_CONFIG_ID and sis.SID_ID = 21 and sis.VALUE = '300111720'
where sic.INTERNAL_COMPANY_ID = 1
and sic.OWNER_ID = 2
and sic.PRODUCT_ID = 320
and sic.LOCATION_ID = 632
and sic.TRACKING_NUMBER = '20150326'
--and sic.INVENTORY_NUMBER = '00546000206305200265'
order by s.UPDATE_TIMESTAMP asc

select sir.*, siri.*, sic._KEY_, siq.QUANTITY
from STOCK_INVENTORY_REQUEST_ITEM siri 
inner join STOCK_INFO si on siri.STOCK_INFO_ID = si.STOCK_INFO_ID
inner join STOCK_INFO_CONFIG sic on si.STOCK_INFO_CONFIG_ID = sic.STOCK_INFO_CONFIG_ID
inner join STOCK_INVENTORY_REQUEST sir on siri.REQUEST_ID = sir.STOCK_INVENTORY_REQUEST_ID
inner join STOCK_INFO_QUANTITY siq on si.BASE_QUANTITY_ID = siq.STOCK_INFO_QUANTITY_ID
--join STOCK_INFO_SID sis on sis.STOCK_INFO_CONFIG_ID = sic.STOCK_INFO_CONFIG_ID and sis.SID_ID = 21 and sis.VALUE = '300111720'
where sic.INTERNAL_COMPANY_ID = 1
and sic.OWNER_ID = 2
and sic.PRODUCT_ID = 320
and sic.LOCATION_ID = 632
and sic.TRACKING_NUMBER = '20150326'
--and sic.INVENTORY_NUMBER = '00546000206305200265'
order by sir.UPDATE_TIMESTAMP asc

-- {"IC":1,"O":2,"P":320,"L":632,"BU":4,"TN":"20150326","IN":"","LOT":"","PD":null,"ED":null,"DI":null,"ST":0,"SU":null,"EU":[{"Id":"5"},{"Id":"6"}],"S":[{"6":"NONE"},{"7":""},{"8":""},{"12":"4"},{"13":"FREE"},{"23":""}]}

-- Find reportings for STOCK_INFO_REQUEST_ID
select * from (
select LOADING_OPERATION_REPORT_ID as RPT_ID, 'Loading' as [TYPE], REPORTED_ID, TRANSPORT_ID, INVENTORY_STATUS, STOCK_INVENTORY_REQUEST_ID, UPDATE_TIMESTAMP from LOADING_OPERATION_REPORT lor
union select DISCHARGING_OPERATION_REPORT_ID, 'Discharging', REPORTED_ID, TRANSPORT_ID, INVENTORY_STATUS, STOCK_INVENTORY_REQUEST_ID, UPDATE_TIMESTAMP from DISCHARGING_OPERATION_REPORT dor
union select VAS_OPERATION_REPORT_ID, 'VAS', vif.STOCK_INFO_ID, '', INVENTORY_STATUS, STOCK_INVENTORY_REQUEST_ID, UPDATE_TIMESTAMP from VAS_OPERATION_REPORT vor join VAS_ITEM_FROM vif on vif.VAS_ITEM_ID = vor.REPORTED_ID
union select STOCK_CHANGE_OPERATION_REPORT_ID, 'Stock-change', sci.FROM_ID, '', INVENTORY_STATUS, STOCK_INVENTORY_REQUEST_ID, scor.UPDATE_TIMESTAMP from STOCK_CHANGE_OPERATION_REPORT scor join STOCK_CHANGE_ITEM sci on scor.REPORTED_ID = sci.STOCK_CHANGE_ITEM_ID
) as rpt
where rpt.STOCK_INVENTORY_REQUEST_ID = 400747

499197	80443	0	NULL	tm	2016-07-11 11:12:34.0000000	tm	2016-07-11 11:12:34.1300000
499198	80444	0	NULL	tm	2016-07-11 11:12:45.0000000	tm	2016-07-11 11:12:45.6700000
499197	499197	7	29287	173101	1	673455	NULL	tm	2016-07-11 11:12:34.0000000	KDirckx	2016-07-11 11:28:14.0500000
499198	499198	7	29287	173101	1	673456	NULL	tm	2016-07-11 11:12:45.0000000	KDirckx	2016-07-11 11:28:14.0500000

-- to change customerinvoice to Excel
update DW_REPORT set ORIGINAL_FILE = 2 where REPORT_KEY = 'CustomerInvoice';
