declare @sidQuaId int = (SELECT STORAGE_IDENTIFIER_ID from STORAGE_IDENTIFIER where CODE = 'QUA')
declare @curUser varchar(20) = 'la180420'
declare @sValues table (val varchar(50));
declare @prdIds table (id int);
insert into @prdIds select PRODUCT_ID from PRODUCT where CODE in ('FMSPAL', 'FMSROL');

/*insert into @sValues values ('10000 SHEETS'),('10500 SHEETS'),('11000 SHEETS'),('11500 SHEETS'),('12000 SHEETS'),('12500 SHEETS'),
	('13000 SHEETS'),('14000 SHEETS'),('1500 SHEETS'),('15000 SHEETS'),('16000 SHEETS'),('17000 SHEETS'),('18000 SHEETS'),('2 PLY'),
	('2000 SHEETS'),('20000 SHEETS'),('23000 SHEETS'),('25000 SHEETS'),('3 PLY EXT FACIAL TIS'),('3000 SHEETS'),('3750 SHEETS'),
	('4000 SHEETS'),('5000 SHEETS'),('5500 SHEETS'),('6000  SHEETS'),('6000 SHEETS'),('6500 SHEETS'),('7000 SHEETS'),('7500 SHEETS'),
	('8000 SHEETS'),('8500 SHEETS'),('9500 SHEETS'),('9750 SHEETS'),('AEGLE PRO 180 G/M2'),('AEGLE PRO 210 G/M2'),('AEGLE PRO 225 G/M2'),
	('AEGLE PRO 235 G/M2'),('AEGLE PRO 245 G/M2'),('AEGLE PRO 260 G/M2'),('AEGLE PRO 270 G/M2'),('AEGLE PRO 280 G/M2'),('AEGLE PRO 290 G/M2'),
	('AEGLE PRO 340 G/M2'),('ANKRAL RE CB B322'),('ANKRAL RE CB B622'),('ANKRAL RE CB P224'),('ANKRAL RE CB P225'),('APPL DRUCK'),
	('COVERLINER BARRIERE'),('CS 125'),('FLEXLINER'),('FLEXLINER COBB60'),('GD2  P I R O L'),('GD250'),('GD3  KOLIBRI'),('GT 300G'),
	('GT2  I B I S'),('HABITO S'),('HAMMERLINER'),('INTERLEAVING PAPER'),('INTERPLAST'),('KT PP ECF'),('MECH. CTD GLOSS'),('MECH. CTD MATT'),
	('NATRONMISCH MG KRAFT'),('NORSTAR 52 G/M'),('PERLEN VALUE'),('PERLENSNOWPRINT HS'),('PERLENVALUE'),('R4 CHORUS CLOSS'),('REY COPY PAPER A4'),
	('SPREE WHITE B'),('SUPERCOBB'),('TAURO'),('TC GR-TOPCOLOR GREAS'),('TESTLINER 3 COBB60'),('TESTLINER EDEWEISS 2'),('TL 130'),('TOILE CLASSIQUE'),
	('TOILE CLASSIQUE 1F'),('VIVALINER'),('WH TOP TESTL B1'),('WH TOP TESTL C1'),('WH TOPTSTLNR TW2000'),('WHITE  TOP KRAFTLINE'),
	('WOODFREE TWO SIDE CO'),('YELLOW DIN');
*/
	
insert into @sValues values ('? SHEETS'),('6000 SHEETS'),('WHITE TOP KRAFTLINE'),('GT2 I B I S'),('GD3 KOLIBRI'),('GD2 P I R O L'),
	('SPREEWHITE B 1800'),('PARLINER'),('RIEGERDIGITAL'),('RIEGER PREMIUM'),('10101/0450');
	
declare @insertedPrValueIds table (id int)	
	
insert into STORAGE_IDENTIFIER_PR_VALUE
	output inserted.STORAGE_IDENTIFIER_PR_VALUE_ID into @insertedPrValueIds
	select @sidQuaId, val, @curUser, getdate(), @curUser, getdate()
	from @sValues sv
	where not exists (select * from STORAGE_IDENTIFIER_PR_VALUE where SID_ID = @sidQuaId and PREDEFINED_VALUE = sv.val);
	
INSERT INTO [dbo].[PRODUCT_SID_SID_VALUE]
		   ([PRODUCT_SID_ID]
		   ,[PREDEFINED_SID_VALUE_ID])
	 select
		   PRODUCT_STORAGE_IDENTIFIER_ID
		   ,ipv.id
	 from
		PRODUCT_STORAGE_IDENTIFIER psi, @prdIds prdIds,	@insertedPrValueIds ipv
	where psi.PRODUCT_ID = prdIds.id and psi.SID_ID = @sidQuaId;
