-- add sids
declare @user nvarchar(15) = 'sys170216';
declare @productGroupCode char(3) = 'SGN'

insert into PRODUCT_STORAGE_IDENTIFIER (PRODUCT_ID, SID_ID, SID_SEQUENCE, IS_MANDATORY, CREATE_USER, CREATE_TIMESTAMP, UPDATE_USER, UPDATE_TIMESTAMP)
	select pgp.PRODUCT_ID, si.STORAGE_IDENTIFIER_ID, 100, 0, @user, GETDATE(), @user, GETDATE() 
	from PRODUCT_GROUP_PRODUCT pgp, PRODUCT_GROUP pg, STORAGE_IDENTIFIER si
	where pgp.PRODUCT_GROUP_ID = pg.PRODUCT_GROUP_ID and pg.CODE = @productGroupCode and si.CODE = 'CTRNO'
insert into PRODUCT_STORAGE_IDENTIFIER (PRODUCT_ID, SID_ID, SID_SEQUENCE, IS_MANDATORY, CREATE_USER, CREATE_TIMESTAMP, UPDATE_USER, UPDATE_TIMESTAMP)
	select pgp.PRODUCT_ID, si.STORAGE_IDENTIFIER_ID, 110, 0, @user, GETDATE(), @user, GETDATE() 
	from PRODUCT_GROUP_PRODUCT pgp, PRODUCT_GROUP pg, STORAGE_IDENTIFIER si
	where pgp.PRODUCT_GROUP_ID = pg.PRODUCT_GROUP_ID and pg.CODE = @productGroupCode and si.CODE = 'DNR'
	
INSERT INTO [dbo].[PRODUCT_SID_OPERATION_TYPE]
		([PRODUCT_SID_ID]
		,[OPERATION_TYPE_ID])
	SELECT
		psi.PRODUCT_STORAGE_IDENTIFIER_ID,
		ot.OPERATION_TYPE_ID
	FROM PRODUCT_STORAGE_IDENTIFIER psi, PRODUCT_GROUP_PRODUCT pgp, PRODUCT_GROUP pg, STORAGE_IDENTIFIER si, OPERATION_TYPE ot
	WHERE psi.PRODUCT_ID = pgp.PRODUCT_ID and pgp.PRODUCT_GROUP_ID = pg.PRODUCT_GROUP_ID and pg.CODE = @productGroupCode
		and psi.SID_ID=si.STORAGE_IDENTIFIER_ID and si.CODE in ('CTRNO', 'DNR')
		and ot.[DESCRIPTION] != 'Additional'

insert into STOCK_INFO_SID (SID_ID, STOCK_INFO_CONFIG_ID, VALUE, CREATE_USER, CREATE_TIMESTAMP, UPDATE_USER, UPDATE_TIMESTAMP)
	select psi.SID_ID, sic.STOCK_INFO_CONFIG_ID, null, @user, GETDATE(), @user, GETDATE()
	from STORAGE_IDENTIFIER si, PRODUCT_STORAGE_IDENTIFIER psi, STOCK_INFO_CONFIG sic, PRODUCT_GROUP_PRODUCT pgp, PRODUCT_GROUP pg
	where pgp.PRODUCT_ID = psi.PRODUCT_ID and psi.SID_ID = si.STORAGE_IDENTIFIER_ID and si.CODE in ('CTRNO', 'DNR')
		and pgp.PRODUCT_ID = sic.PRODUCT_ID and pgp.PRODUCT_GROUP_ID = pg.PRODUCT_GROUP_ID and pg.CODE = @productGroupCode
		
-- after the script is run recalc keys for productgroup = 2 ('SGN')
-- after that rebuild stock and reservations indexes