--t.3117 - update remaining qty
update siq set QUANTITY = 1
from OPERATION_PLAN op join DISCHARGING_OPERATION_PLAN dop on op.OPERATION_PLAN_ID = dop.DISCHARGING_OPERATION_PLAN_ID and op.ORDER_ITEM_ID = 143211
	join STOCK_INFO si on dop.REMAINING_ID = si.STOCK_INFO_ID 
	join STOCK_INFO_QUANTITY siq on si.BASE_QUANTITY_ID = siq.STOCK_INFO_QUANTITY_ID
	--join STOCK_INFO_CONFIG sic on si.STOCK_INFO_CONFIG_ID = sic.STOCK_INFO_CONFIG_ID
	--join STOCK_INFO_SID sis on si.STOCK_INFO_CONFIG_ID = sis.STOCK_INFO_CONFIG_ID and sis.SID_ID = 4 
	left join OPERATION_REPORT rpt on op.OPERATION_PLAN_ID = rpt.PLAN_ID
	where OPERATION_REPORT_ID is null