select * from INTERNAL_COMPANY ic join COMPANY c on ic.COMPANY_ID = c.COMPANY_ID
select top 5 * from ATTACHMENT order by 1 desc
select * from CUSTOMER_FINANCIAL_DOCUMENT_SETTINGS

update COMPANY set CUSTOMER_FINANCIAL_DOCUMENT_SETTINGS_ID = 1 where COMPANY_ID = 1
update COMPANY set CUSTOMER_FINANCIAL_DOCUMENT_SETTINGS_ID = 2 where COMPANY_ID = 220
update COMPANY set CUSTOMER_FINANCIAL_DOCUMENT_SETTINGS_ID = 3 where COMPANY_ID = 246
update COMPANY set CUSTOMER_FINANCIAL_DOCUMENT_SETTINGS_ID = 4 where COMPANY_ID = 299

update ATTACHMENT set FILE_PATH = CAST(ATTACHMENT_ID as VARCHAR) + '_' + FILE_NAME where ATTACHMENT_ID > 417