-- remove foreign keys
ALTER TABLE [dbo].[ORDER_HTTP_LOG_ITEM] DROP CONSTRAINT [FK_ORDER_HTTP_LOG_ITEM_HTTP_LOG_ITEM]
ALTER TABLE [dbo].[ORDER_HTTP_LOG_ITEM] DROP CONSTRAINT [FK_ORDER_HTTP_LOG_ITEM_ORDERS]
ALTER TABLE [dbo].[ORDER_ITEM_HTTP_LOG_ITEM] DROP CONSTRAINT [FK_ORDER_ITEM_HTTP_LOG_ITEM_HTTP_LOG_ITEM]
ALTER TABLE [dbo].[ORDER_ITEM_HTTP_LOG_ITEM] DROP CONSTRAINT [FK_ORDER_ITEM_HTTP_LOG_ITEM_ORDER_ITEM]
ALTER TABLE [dbo].[TRANSPORT_HTTP_LOG_ITEM] DROP CONSTRAINT [FK_TRANSPORT_HTTP_LOG_ITEM_TRANSPORT]
ALTER TABLE [dbo].[TRANSPORT_HTTP_LOG_ITEM] DROP CONSTRAINT [FK_TRANSPORT_HTTP_LOG_ITEM_HTTP_LOG_ITEM]
ALTER TABLE [dbo].[TRANSPORT_WEIGHNING] DROP CONSTRAINT [FK_TRANSPORT_WEIGHNING_HTTP_LOG_ITEM]
GO

-- add foreign keys
/*ALTER TABLE [dbo].[ORDER_HTTP_LOG_ITEM]  WITH CHECK ADD  CONSTRAINT [FK_ORDER_HTTP_LOG_ITEM_HTTP_LOG_ITEM] FOREIGN KEY([HTTP_LOG_ITEM_ID])
REFERENCES [dbo].[HTTP_LOG_ITEM] ([HTTP_LOG_ITEM_ID])
GO

ALTER TABLE [dbo].[ORDER_HTTP_LOG_ITEM] CHECK CONSTRAINT [FK_ORDER_HTTP_LOG_ITEM_HTTP_LOG_ITEM]
GO


ALTER TABLE [dbo].[ORDER_HTTP_LOG_ITEM]  WITH CHECK ADD  CONSTRAINT [FK_ORDER_HTTP_LOG_ITEM_ORDERS] FOREIGN KEY([ORDER_ID])
REFERENCES [dbo].[ORDERS] ([ORDER_ID])
GO

ALTER TABLE [dbo].[ORDER_HTTP_LOG_ITEM] CHECK CONSTRAINT [FK_ORDER_HTTP_LOG_ITEM_ORDERS]
ALTER TABLE [dbo].[ORDER_ITEM_HTTP_LOG_ITEM]  WITH CHECK ADD  CONSTRAINT [FK_ORDER_ITEM_HTTP_LOG_ITEM_HTTP_LOG_ITEM] FOREIGN KEY([HTTP_LOG_ITEM_ID])
REFERENCES [dbo].[HTTP_LOG_ITEM] ([HTTP_LOG_ITEM_ID])
GO

ALTER TABLE [dbo].[ORDER_ITEM_HTTP_LOG_ITEM] CHECK CONSTRAINT [FK_ORDER_ITEM_HTTP_LOG_ITEM_HTTP_LOG_ITEM]
ALTER TABLE [dbo].[ORDER_ITEM_HTTP_LOG_ITEM]  WITH CHECK ADD  CONSTRAINT [FK_ORDER_ITEM_HTTP_LOG_ITEM_ORDER_ITEM] FOREIGN KEY([ORDER_ITEM_ID])
REFERENCES [dbo].[ORDER_ITEM] ([ORDER_ITEM_ID])
GO

ALTER TABLE [dbo].[ORDER_ITEM_HTTP_LOG_ITEM] CHECK CONSTRAINT [FK_ORDER_ITEM_HTTP_LOG_ITEM_ORDER_ITEM]
ALTER TABLE [dbo].[TRANSPORT_HTTP_LOG_ITEM]  WITH CHECK ADD  CONSTRAINT [FK_TRANSPORT_HTTP_LOG_ITEM_TRANSPORT] FOREIGN KEY([TRANSPORT_ID])
REFERENCES [dbo].[TRANSPORT] ([TRANSPORT_ID])
ON DELETE CASCADE
GO

ALTER TABLE [dbo].[TRANSPORT_HTTP_LOG_ITEM] CHECK CONSTRAINT [FK_TRANSPORT_HTTP_LOG_ITEM_TRANSPORT]
ALTER TABLE [dbo].[TRANSPORT_WEIGHNING]  WITH CHECK ADD  CONSTRAINT [FK_TRANSPORT_WEIGHNING_HTTP_LOG_ITEM] FOREIGN KEY([HTTP_LOG_ITEM_ID])
REFERENCES [dbo].[HTTP_LOG_ITEM] ([HTTP_LOG_ITEM_ID])
GO

ALTER TABLE [dbo].[TRANSPORT_WEIGHNING] CHECK CONSTRAINT [FK_TRANSPORT_WEIGHNING_HTTP_LOG_ITEM]
*/
