delete tpv from TRANSPORT_PROPERTY_VALUE tpv join TRANSPORT t on tpv.TRANSPORT_ID = t.TRANSPORT_ID and t.TRANSPORT_TYPE_ID in (10, 11)
	join TRANSPORT_PROPERTY_DF tpd on tpv.TRANSPORT_PROPERTY_ID = tpd.TRANSPORT_PROPERTY_ID and tpd.SEQUENCE > 200
delete from TRANSPORT_PROPERTY_DF where TRANSPORT_TYPE_ID in (10,11) and SEQUENCE > 200