select * into bak_pg_company from PRODUCT_GROUP_COMPANY

insert into PRODUCT_GROUP_COMPANY (PRODUCT_GROUP_ID, COMPANYNR, CREATE_USER, CREATE_TIMESTAMP, UPDATE_USER, UPDATE_TIMESTAMP)
select pg.PRODUCT_GROUP_ID, c.COMPANYNR, 'sys160408', getdate(), 'sys160408', getdate()
from PRODUCT_GROUP pg, COMPANY c
where pg.CODE = 'ALBEM' and c.CODE = 'ALBEM'

insert into PRODUCT_GROUP_COMPANY (PRODUCT_GROUP_ID, COMPANYNR, CREATE_USER, CREATE_TIMESTAMP, UPDATE_USER, UPDATE_TIMESTAMP)
select pg.PRODUCT_GROUP_ID, c.COMPANYNR, 'sys160408', getdate(), 'sys160408', getdate()
from PRODUCT_GROUP pg, COMPANY c
where pg.CODE = 'CRI' and c.CODE = 'CRI'

insert into PRODUCT_GROUP_COMPANY (PRODUCT_GROUP_ID, COMPANYNR, CREATE_USER, CREATE_TIMESTAMP, UPDATE_USER, UPDATE_TIMESTAMP)
select pg.PRODUCT_GROUP_ID, c.COMPANYNR, 'sys160408', getdate(), 'sys160408', getdate()
from PRODUCT_GROUP pg, COMPANY c
where pg.CODE = 'FUJI' and c.CODE = 'FUJI'

--drop table bak_pg_company