update STORAGE_IDENTIFIER_PR_VALUE set PREDEFINED_VALUE = 'OUTBACK 2-WAY' where SID_ID = 7 and PREDEFINED_VALUE = 'P-4 WAY OUTBACK'
update STOCK_INFO_SID set [VALUE] = 'OUTBACK 2-WAY', UPDATE_USER = 'sys_160330', UPDATE_TIMESTAMP = GETDATE() where SID_ID = 7 and [VALUE] = 'P-4 WAY OUTBACK'
update STOCK_INFO_CONFIG set [_KEY_] = REPLACE([_KEY_], '{"7":"P-4 WAY OUTBACK"}', '{"7":"OUTBACK 2-WAY"}'), UPDATE_USER = 'sys_160330', UPDATE_TIMESTAMP = GETDATE()
