
SELECT t.TARIFF_ID, dt.TYPE, o.CODE as OP_CODE, o.NAME as OP_NAME, t.STATUS, t.PERIOD_FROM, t.PERIOD_TO,
	ti.TARIFF_INFO_ID, ti.CODE, ti.DESCRIPTION, ti.TARIFF, ti.UNIT_ID, ti.MEASUREMENT_UNIT_ID as MEAS_U, ti.CURRENCY_ID, ti.SERVICE_ACCOUNT,
	tr.TARIFF_RANGE_ID, tr.TARIFF, tr.RANGE_FROM, tr.RANGE_TO, tr.UNIT_ID, tr.MEASUREMENT_UNIT_ID,
	tf.TARIFF_FILE_ID, tf.DESCRIPTION, tf.REFERENCE, tf.STATUS, tf.INTERNAL_COMPANY_ID, tf.OPERATION_TYPE_ID,
	tc.COMPANY_ID as CUSTOMER_ID, c.CODE, c.NAME,
	si.STOCK_INFO_ID, si.STOCK_INFO_CONFIG_ID, 
	sic.INTERNAL_COMPANY_ID, sic.PRODUCT_ID, sic.OWNER_ID, sic.LOCATION_ID, sic.STATUS, sic.STORAGE_UNIT_ID
	--t.CREATE_USER, t.CREATE_TIMESTAMP, t.UPDATE_USER, t.UPDATE_TIMESTAMP
FROM TARIFF t
JOIN
(
select DISCHARGING_TARIFF_ID as TARIFF_ID, STOCK_INFO_ID, 'DISCH' as TYPE from DISCHARGING_TARIFF
union
select LOADING_TARIFF_ID, STOCK_INFO_ID, 'LOAD' from LOADING_TARIFF
union
select VAS_TARIFF_ID, null, 'VAS' from VAS_TARIFF
union
select STOCK_CHANGE_TARIFF_ID, null, 'SC' from STOCK_CHANGE_TARIFF
union
select ADDITIONAL_TARIFF_ID, null, 'ADIT' from ADDITIONAL_TARIFF
union
select ADMINISTRATIVE_TARIFF_ID, null, 'ADMIN' from ADMINISTRATIVE_TARIFF
union
select WAREHOUSE_RENT_TARIFF_ID, STOCK_INFO_ID, 'WHR' from WAREHOUSE_RENT_TARIFF
) as dt on t.TARIFF_ID = dt.TARIFF_ID
LEFT JOIN STOCK_INFO si ON dt.STOCK_INFO_ID = si.STOCK_INFO_ID
LEFT JOIN STOCK_INFO_CONFIG sic ON si.STOCK_INFO_CONFIG_ID = sic.STOCK_INFO_CONFIG_ID
--LEFT JOIN PRODUCT p ON sic.PRODUCT_ID = p.PRODUCT_ID
--LEFT JOIN UNIT u ON sic.STORAGE_UNIT_ID = u.UNIT_ID
JOIN TARIFF_INFO ti ON t.TARIFF_INFO_ID = ti.TARIFF_INFO_ID
LEFT JOIN TARIFF_INFO_RANGE tir ON ti.TARIFF_INFO_ID = tir.TARIFF_INFO_ID
LEFT JOIN TARIFF_RANGE tr ON tir.TARIFF_RANGE_ID = tr.TARIFF_RANGE_ID
--LEFT JOIN UNIT tiu ON ti.UNIT_ID = tiu.UNIT_ID
--LEFT JOIN MEASUREMENT_UNIT mu ON ti.MEASUREMENT_UNIT_ID = mu.MEASUREMENT_UNIT_ID
JOIN TARIFF_FILE tf ON t.TARIFF_FILE_ID = tf.TARIFF_FILE_ID 
--JOIN INTERNAL_COMPANY ic ON tf.INTERNAL_COMPANY_ID = ic.COMPANYNR
--JOIN COMPANY icc ON ic.COMPANYNR = icc.COMPANYNR
LEFT JOIN TARIFF_CUSTOMER tc ON tc.TARIFF_ID = t.TARIFF_ID
LEFT JOIN COMPANY c ON tc.COMPANY_ID = c.COMPANYNR
LEFT JOIN OPERATION o ON t.OPERATION_ID = o.OPERATION_ID
ORDER BY 1
