
SELECT t.TARIFF_ID, dt.TYPE, o.CODE as OP_CODE, o.NAME as OP_NAME, t.STATUS, t.PERIOD_FROM, t.PERIOD_TO,
	ti.TARIFF_INFO_ID, ti.CODE, ti.DESCRIPTION, ti.TARIFF, ti.UNIT_ID, ti.MEASUREMENT_UNIT_ID as MEAS_U, ti.CURRENCY_ID, ti.SERVICE_ACCOUNT,
	tr.TARIFF_RANGE_ID, tr.TARIFF, tr.RANGE_FROM, tr.RANGE_TO, tr.UNIT_ID, tr.MEASUREMENT_UNIT_ID,
	tf.TARIFF_FILE_ID, tf.DESCRIPTION, tf.REFERENCE, tf.STATUS, tf.INTERNAL_COMPANY_ID, tf.OPERATION_TYPE_ID,
	tc.COMPANY_ID as CUSTOMER_ID, c.CODE, c.NAME,
	si.STOCK_INFO_ID, si.STOCK_INFO_CONFIG_ID, 
	sic.INTERNAL_COMPANY_ID, sic.PRODUCT_ID, sic.OWNER_ID, sic.LOCATION_ID, sic.STATUS, sic.STORAGE_UNIT_ID
	--t.CREATE_USER, t.CREATE_TIMESTAMP, t.UPDATE_USER, t.UPDATE_TIMESTAMP
FROM TARIFF t
JOIN
(
select DISCHARGING_TARIFF_ID as TARIFF_ID, STOCK_INFO_ID, 'DISCH' as TYPE from DISCHARGING_TARIFF
union
select LOADING_TARIFF_ID, STOCK_INFO_ID, 'LOAD' from LOADING_TARIFF
union
select VAS_TARIFF_ID, null, 'VAS' from VAS_TARIFF
union
select STOCK_CHANGE_TARIFF_ID, null, 'SC' from STOCK_CHANGE_TARIFF
union
select ADDITIONAL_TARIFF_ID, null, 'ADIT' from ADDITIONAL_TARIFF
union
select ADMINISTRATIVE_TARIFF_ID, null, 'ADMIN' from ADMINISTRATIVE_TARIFF
union
select WAREHOUSE_RENT_TARIFF_ID, STOCK_INFO_ID, 'WHR' from WAREHOUSE_RENT_TARIFF
) as dt on t.TARIFF_ID = dt.TARIFF_ID
LEFT JOIN STOCK_INFO si ON dt.STOCK_INFO_ID = si.STOCK_INFO_ID
LEFT JOIN STOCK_INFO_CONFIG sic ON si.STOCK_INFO_CONFIG_ID = sic.STOCK_INFO_CONFIG_ID
--LEFT JOIN PRODUCT p ON sic.PRODUCT_ID = p.PRODUCT_ID
--LEFT JOIN UNIT u ON sic.STORAGE_UNIT_ID = u.UNIT_ID
JOIN TARIFF_INFO ti ON t.TARIFF_INFO_ID = ti.TARIFF_INFO_ID
LEFT JOIN TARIFF_INFO_RANGE tir ON ti.TARIFF_INFO_ID = tir.TARIFF_INFO_ID
LEFT JOIN TARIFF_RANGE tr ON tir.TARIFF_RANGE_ID = tr.TARIFF_RANGE_ID
--LEFT JOIN UNIT tiu ON ti.UNIT_ID = tiu.UNIT_ID
--LEFT JOIN MEASUREMENT_UNIT mu ON ti.MEASUREMENT_UNIT_ID = mu.MEASUREMENT_UNIT_ID
JOIN TARIFF_FILE tf ON t.TARIFF_FILE_ID = tf.TARIFF_FILE_ID 
--JOIN INTERNAL_COMPANY ic ON tf.INTERNAL_COMPANY_ID = ic.COMPANYNR
--JOIN COMPANY icc ON ic.COMPANYNR = icc.COMPANYNR
LEFT JOIN TARIFF_CUSTOMER tc ON tc.TARIFF_ID = t.TARIFF_ID
LEFT JOIN COMPANY c ON tc.COMPANY_ID = c.COMPANYNR
LEFT JOIN OPERATION o ON t.OPERATION_ID = o.OPERATION_ID
ORDER BY 1

-- ver 2
SELECT t.TARIFF_ID as T_ID, et.TYPE as Trf_TYPE,
	ti.TARIFF_INFO_ID, ti.CODE as TI_CODE, ti.DESCRIPTION as TI_DESCR,  ti.TARIFF as TI_TARIFF, ti.UNIT_ID as TI_U_ID, tiu.CODE as TI_U_CODE,
	ti.MEASUREMENT_UNIT_ID as TI_MU_ID, mu.[DESCRIPTION] as TI_MU_DESC,
	et.TR_TYPES,
	ti.SERVICE_ACCOUNT,
	stuff((select ', ' + CODE from TARIFF_CUSTOMER tci join COMPANY ci on tci.COMPANY_ID = ci.COMPANYNR and tci.TARIFF_ID = t.TARIFF_ID for XML PATH('')), 1, 2, '') as CUSTRs,
	tf.TARIFF_FILE_ID, tf.REFERENCE as TF_REF, tf.OPERATION_TYPE_ID as TF_OPER_TYP_ID, ot.[DESCRIPTION] as TF_OP_TYP, c.CODE as TF_IC_CODE, --tf.STATUS as TF_STATUS, tf.INTERNAL_COMPANY_ID as TF_IC, tf.DESCRIPTION as TF_DESCR,
	si.STOCK_INFO_ID, si.STOCK_INFO_CONFIG_ID, 
	sic.INTERNAL_COMPANY_ID as SIC_IC, sic.PRODUCT_ID, p.CODE, p.SHORT_DESC, sic.OWNER_ID, sic.LOCATION_ID, sic.STATUS, sic.STORAGE_UNIT_ID, u.CODE as STOR_U,
	o.NAME as OP_NAME, --o.CODE as OP_CODE,
	t.STATUS, t.PERIOD_FROM, t.PERIOD_TO,
	tr.TARIFF_RANGE_ID, tr.TARIFF, tr.RANGE_FROM, tr.RANGE_TO, tr.UNIT_ID, tru.CODE as RANGE_UNIT, tr.MEASUREMENT_UNIT_ID, trmu.[DESCRIPTION] as RANGE_MU
FROM TARIFF t join
(
select lt.LOADING_TARIFF_ID, 'Load' as TYPE, STOCK_INFO_ID,
	stuff((select ', ' + [DESCRIPTION] from TRANSPORT_TYPE tt join LOADING_TARIFF_TRANSPORT_TYPE lttt
		on tt.TRANSPORT_TYPE_ID = lttt.TRANSPORT_TYPE_ID and lttt.LOADING_TARIFF_ID = lt.LOADING_TARIFF_ID
		for XML PATH ('')), 1, 2, '') as TR_TYPES
 from LOADING_TARIFF lt
union
select dt.DISCHARGING_TARIFF_ID, 'Disch', STOCK_INFO_ID, 
	stuff((select ', ' + [DESCRIPTION] from TRANSPORT_TYPE tt join DISCHARGING_TARIFF_TRANSPORT_TYPE dttt
		on tt.TRANSPORT_TYPE_ID = dttt.TRANSPORT_TYPE_ID and dttt.DISCHARGING_TARIFF_ID = dt.DISCHARGING_TARIFF_ID
		for XML PATH ('')), 1, 2, '') as TR_TYPES
 from DISCHARGING_TARIFF dt
union
select VAS_TARIFF_ID, 'VAS', null, null from VAS_TARIFF
union
select STOCK_CHANGE_TARIFF_ID, 'SC', null, null from STOCK_CHANGE_TARIFF
union
select ADDITIONAL_TARIFF_ID, 'Add', null, null from ADDITIONAL_TARIFF
union
select ADMINISTRATIVE_TARIFF_ID, 'Adm', null, null from ADMINISTRATIVE_TARIFF
union
select WAREHOUSE_RENT_TARIFF_ID, 'W', STOCK_INFO_ID, null from WAREHOUSE_RENT_TARIFF
) et on t.TARIFF_ID = et.LOADING_TARIFF_ID
JOIN TARIFF_INFO ti ON t.TARIFF_INFO_ID = ti.TARIFF_INFO_ID
JOIN TARIFF_FILE tf ON t.TARIFF_FILE_ID = tf.TARIFF_FILE_ID 
JOIN COMPANY c ON tf.INTERNAL_COMPANY_ID = c.COMPANYNR
LEFT JOIN OPERATION_TYPE ot ON tf.OPERATION_TYPE_ID = ot.OPERATION_TYPE_ID
LEFT JOIN OPERATION o ON t.OPERATION_ID = o.OPERATION_ID
LEFT JOIN STOCK_INFO si ON et.STOCK_INFO_ID = si.STOCK_INFO_ID
LEFT JOIN STOCK_INFO_CONFIG sic ON si.STOCK_INFO_CONFIG_ID = sic.STOCK_INFO_CONFIG_ID
LEFT JOIN PRODUCT p ON sic.PRODUCT_ID = p.PRODUCT_ID
LEFT JOIN UNIT u ON sic.STORAGE_UNIT_ID = u.UNIT_ID
LEFT JOIN UNIT tiu ON ti.UNIT_ID = tiu.UNIT_ID
LEFT JOIN MEASUREMENT_UNIT mu ON ti.MEASUREMENT_UNIT_ID = mu.MEASUREMENT_UNIT_ID
LEFT JOIN TARIFF_INFO_RANGE tir ON ti.TARIFF_INFO_ID = tir.TARIFF_INFO_ID
LEFT JOIN TARIFF_RANGE tr ON tir.TARIFF_RANGE_ID = tr.TARIFF_RANGE_ID
LEFT JOIN UNIT tru ON tr.UNIT_ID = tru.UNIT_ID
LEFT JOIN MEASUREMENT_UNIT trmu ON tr.MEASUREMENT_UNIT_ID = trmu.MEASUREMENT_UNIT_ID
--join TARIFF_CUSTOMER tc on t.TARIFF_ID = tc.TARIFF_ID and tc.COMPANY_ID = 585 -- in (2, 3)
--where ti.CODE in ('POIADM2', 'BREDC', 'CHEMADD1', 'LOADRAVAGO', 'NEUTRKOD', 'AOTRHALBM')
--where tf.INTERNAL_COMPANY_ID = 1
ORDER BY 4

-- ver 3
SELECT t.TARIFF_ID as T_ID, et.TYPE as Trf_TYPE,
	ti.TARIFF_INFO_ID, ti.CODE as TI_CODE, ti.DESCRIPTION as TI_DESCR,  ti.TARIFF as TI_TARIFF, ti.UNIT_ID as TI_U_ID, tiu.CODE as TI_U_CODE,
	ti.MEASUREMENT_UNIT_ID as TI_MU_ID, mu.[DESCRIPTION] as TI_MU_DESC,
	et.TR_TYPES,
	ti.SERVICE_ACCOUNT,
	stuff((select ', ' + CODE from TARIFF_CUSTOMER tci join COMPANY ci on tci.COMPANY_ID = ci.COMPANY_ID and tci.TARIFF_ID = t.TARIFF_ID for XML PATH('')), 1, 2, '') as CUSTRs,
	--tf.TARIFF_FILE_ID, tf.REFERENCE as TF_REF, tf.OPERATION_TYPE_ID as TF_OPER_TYP_ID,
	--ot.[DESCRIPTION] as TF_OP_TYP, c.CODE as TF_IC_CODE, --tf.STATUS as TF_STATUS, tf.INTERNAL_COMPANY_ID as TF_IC, tf.DESCRIPTION as TF_DESCR,
	--si.STOCK_INFO_ID, si.STOCK_INFO_CONFIG_ID, 
	--sic.INTERNAL_COMPANY_ID as SIC_IC, sic.PRODUCT_ID, p.CODE, p.SHORT_DESC, sic.OWNER_ID, sic.LOCATION_ID, sic.STATUS, sic.STORAGE_UNIT_ID, u.CODE as STOR_U,
	tsi.PRODUCT_ID, tsi.OWNER_ID, tsi.LOCATION_ID,
	o.NAME as OP_NAME, --o.CODE as OP_CODE,
	t.STATUS, t.PERIOD_FROM, t.PERIOD_TO,
	tr.TARIFF_RANGE_ID, tr.TARIFF, tr.RANGE_FROM, tr.RANGE_TO, tr.UNIT_ID, tru.CODE as RANGE_UNIT, tr.MEASUREMENT_UNIT_ID, trmu.[DESCRIPTION] as RANGE_MU
FROM TARIFF t join
(
select lt.LOADING_TARIFF_ID, 'Load' as TYPE, TARIFF_STOCK_INFO_ID,
	stuff((select ', ' + [DESCRIPTION] from TRANSPORT_TYPE tt join LOADING_TARIFF_TRANSPORT_TYPE lttt
		on tt.TRANSPORT_TYPE_ID = lttt.TRANSPORT_TYPE_ID and lttt.LOADING_TARIFF_ID = lt.LOADING_TARIFF_ID
		for XML PATH ('')), 1, 2, '') as TR_TYPES
 from LOADING_TARIFF lt
union
select dt.DISCHARGING_TARIFF_ID, 'Disch', TARIFF_STOCK_INFO_ID, 
	stuff((select ', ' + [DESCRIPTION] from TRANSPORT_TYPE tt join DISCHARGING_TARIFF_TRANSPORT_TYPE dttt
		on tt.TRANSPORT_TYPE_ID = dttt.TRANSPORT_TYPE_ID and dttt.DISCHARGING_TARIFF_ID = dt.DISCHARGING_TARIFF_ID
		for XML PATH ('')), 1, 2, '') as TR_TYPES
 from DISCHARGING_TARIFF dt
union
select VAS_TARIFF_ID, 'VAS', null, null from VAS_TARIFF
union
select STOCK_CHANGE_TARIFF_ID, 'SC', null, null from STOCK_CHANGE_TARIFF
union
select ADDITIONAL_TARIFF_ID, 'Add', null, null from ADDITIONAL_TARIFF
union
select ADMINISTRATIVE_TARIFF_ID, 'Adm', null, null from ADMINISTRATIVE_TARIFF
union
select WAREHOUSE_RENT_TARIFF_ID, 'W', TARIFF_STOCK_INFO_ID, null from WAREHOUSE_RENT_TARIFF
) et on t.TARIFF_ID = et.LOADING_TARIFF_ID
JOIN TARIFF_INFO ti ON t.TARIFF_INFO_ID = ti.TARIFF_INFO_ID
--JOIN TARIFF_FILE tf ON t.TARIFF_FILE_ID = tf.TARIFF_FILE_ID 
--JOIN COMPANY c ON tf.INTERNAL_COMPANY_ID = c.COMPANYNR
--LEFT JOIN OPERATION_TYPE ot ON tf.OPERATION_TYPE_ID = ot.OPERATION_TYPE_ID
LEFT JOIN OPERATION o ON t.OPERATION_ID = o.OPERATION_ID
LEFT JOIN TARIFF_STOCK_INFO tsi ON et.TARIFF_STOCK_INFO_ID = tsi.TARIFF_STOCK_INFO_ID
--LEFT JOIN STOCK_INFO_CONFIG sic ON si.STOCK_INFO_CONFIG_ID = sic.STOCK_INFO_CONFIG_ID
LEFT JOIN PRODUCT p ON tsi.PRODUCT_ID = p.PRODUCT_ID
--LEFT JOIN UNIT u ON sic.STORAGE_UNIT_ID = u.UNIT_ID
LEFT JOIN UNIT tiu ON ti.UNIT_ID = tiu.UNIT_ID
LEFT JOIN MEASUREMENT_UNIT mu ON ti.MEASUREMENT_UNIT_ID = mu.MEASUREMENT_UNIT_ID
LEFT JOIN TARIFF_INFO_RANGE tir ON ti.TARIFF_INFO_ID = tir.TARIFF_INFO_ID
LEFT JOIN TARIFF_RANGE tr ON tir.TARIFF_RANGE_ID = tr.TARIFF_RANGE_ID
LEFT JOIN UNIT tru ON tr.UNIT_ID = tru.UNIT_ID
LEFT JOIN MEASUREMENT_UNIT trmu ON tr.MEASUREMENT_UNIT_ID = trmu.MEASUREMENT_UNIT_ID
join TARIFF_CUSTOMER tc on t.TARIFF_ID = tc.TARIFF_ID and tc.COMPANY_ID = 516 
--where ti.CODE in ('POIADM2', 'BREDC', 'CHEMADD1', 'LOADRAVAGO', 'NEUTRKOD', 'AOTRHALBM')
--where tf.INTERNAL_COMPANY_ID = 1
where (PERIOD_FROM<getdate() and PERIOD_TO > getdate())
ORDER BY 4

-- ver 4
SELECT t.TARIFF_ID as T_ID, et.TYPE as Trf_TYPE,
	ti.TARIFF_INFO_ID, ti.CODE as TI_CODE, ti.DESCRIPTION as TI_DESCR,  ti.TARIFF as TI_TARIFF, ti.UNIT_ID as TI_U_ID, tiu.CODE as TI_U_CODE,
	ti.MEASUREMENT_UNIT_ID as TI_MU_ID, mu.[DESCRIPTION] as TI_MU_DESC,
	et.TR_TYPES,
	ti.SERVICE_ACCOUNT,
	stuff((select ', ' + CODE from TARIFF_CUSTOMER tci join COMPANY ci on tci.COMPANY_ID = ci.COMPANY_ID and tci.TARIFF_ID = t.TARIFF_ID for XML PATH('')), 1, 2, '') as CUSTRs,
	--tf.TARIFF_FILE_ID, tf.REFERENCE as TF_REF, tf.OPERATION_TYPE_ID as TF_OPER_TYP_ID,
	--ot.[DESCRIPTION] as TF_OP_TYP, c.CODE as TF_IC_CODE, --tf.STATUS as TF_STATUS, tf.INTERNAL_COMPANY_ID as TF_IC, tf.DESCRIPTION as TF_DESCR,
	--si.STOCK_INFO_ID, si.STOCK_INFO_CONFIG_ID, 
	--sic.INTERNAL_COMPANY_ID as SIC_IC, sic.PRODUCT_ID, p.CODE, p.SHORT_DESC, sic.OWNER_ID, sic.LOCATION_ID, sic.STATUS, sic.STORAGE_UNIT_ID, u.CODE as STOR_U,
	tsipg.PRODUCT_GROUP_ID, tsippv.PRODUCT_PROPERTY_ID, tsippv.VALUE, tsis.SID_ID, tsis.VALUE, tsibu.UNIT_ID as BASE_UNIT_ID, tsisu.UNIT_ID as STOR_UNIT_ID,
	tsi.PRODUCT_ID, tsi.OWNER_ID, tsi.LOCATION_ID,
	o.NAME as OP_NAME, --o.CODE as OP_CODE,
	t.STATUS, t.PERIOD_FROM, t.PERIOD_TO,
	tr.TARIFF_RANGE_ID, tr.TARIFF, tr.RANGE_FROM, tr.RANGE_TO, tr.UNIT_ID, tru.CODE as RANGE_UNIT, tr.MEASUREMENT_UNIT_ID, trmu.[DESCRIPTION] as RANGE_MU
FROM TARIFF t join
(
select lt.LOADING_TARIFF_ID, 'Load' as TYPE, TARIFF_STOCK_INFO_ID,
	stuff((select ', ' + [DESCRIPTION] from TRANSPORT_TYPE tt join LOADING_TARIFF_TRANSPORT_TYPE lttt
		on tt.TRANSPORT_TYPE_ID = lttt.TRANSPORT_TYPE_ID and lttt.LOADING_TARIFF_ID = lt.LOADING_TARIFF_ID
		for XML PATH ('')), 1, 2, '') as TR_TYPES
 from LOADING_TARIFF lt
union
select dt.DISCHARGING_TARIFF_ID, 'Disch', TARIFF_STOCK_INFO_ID, 
	stuff((select ', ' + [DESCRIPTION] from TRANSPORT_TYPE tt join DISCHARGING_TARIFF_TRANSPORT_TYPE dttt
		on tt.TRANSPORT_TYPE_ID = dttt.TRANSPORT_TYPE_ID and dttt.DISCHARGING_TARIFF_ID = dt.DISCHARGING_TARIFF_ID
		for XML PATH ('')), 1, 2, '') as TR_TYPES
 from DISCHARGING_TARIFF dt
union
select VAS_TARIFF_ID, 'VAS', null, null from VAS_TARIFF
union
select STOCK_CHANGE_TARIFF_ID, 'SC', null, null from STOCK_CHANGE_TARIFF
union
select ADDITIONAL_TARIFF_ID, 'Add', null, null from ADDITIONAL_TARIFF
union
select ADMINISTRATIVE_TARIFF_ID, 'Adm', null, null from ADMINISTRATIVE_TARIFF
union
select WAREHOUSE_RENT_TARIFF_ID, 'W', TARIFF_STOCK_INFO_ID, null from WAREHOUSE_RENT_TARIFF
) et on t.TARIFF_ID = et.LOADING_TARIFF_ID
JOIN TARIFF_INFO ti ON t.TARIFF_INFO_ID = ti.TARIFF_INFO_ID
--JOIN TARIFF_FILE tf ON t.TARIFF_FILE_ID = tf.TARIFF_FILE_ID 
--JOIN COMPANY c ON tf.INTERNAL_COMPANY_ID = c.COMPANYNR
--LEFT JOIN OPERATION_TYPE ot ON tf.OPERATION_TYPE_ID = ot.OPERATION_TYPE_ID
left join TARIFF_SI_PRODUCT_GROUP tsipg on et.TARIFF_STOCK_INFO_ID = tsipg.TARIFF_STOCK_INFO_ID
left join TARIFF_PRODUCT_PROPERTY_VALUE tsippv on et.TARIFF_STOCK_INFO_ID = tsippv.TARIFF_STOCK_INFO_ID
left join TARIFF_SID tsis on et.TARIFF_STOCK_INFO_ID = tsis.TARIFF_STOCK_INFO_ID
left join TARIFF_SI_BASE_UNIT tsibu on et.TARIFF_STOCK_INFO_ID = tsibu.TARIFF_STOCK_INFO_ID
left join TARIFF_SI_STORAGE_UNIT tsisu on et.TARIFF_STOCK_INFO_ID = tsisu.TARIFF_STOCK_INFO_ID
LEFT JOIN OPERATION o ON t.OPERATION_ID = o.OPERATION_ID
LEFT JOIN TARIFF_STOCK_INFO tsi ON et.TARIFF_STOCK_INFO_ID = tsi.TARIFF_STOCK_INFO_ID
--LEFT JOIN STOCK_INFO_CONFIG sic ON si.STOCK_INFO_CONFIG_ID = sic.STOCK_INFO_CONFIG_ID
LEFT JOIN PRODUCT p ON tsi.PRODUCT_ID = p.PRODUCT_ID
--LEFT JOIN UNIT u ON sic.STORAGE_UNIT_ID = u.UNIT_ID
LEFT JOIN UNIT tiu ON ti.UNIT_ID = tiu.UNIT_ID
LEFT JOIN MEASUREMENT_UNIT mu ON ti.MEASUREMENT_UNIT_ID = mu.MEASUREMENT_UNIT_ID
LEFT JOIN TARIFF_INFO_RANGE tir ON ti.TARIFF_INFO_ID = tir.TARIFF_INFO_ID
LEFT JOIN TARIFF_RANGE tr ON tir.TARIFF_RANGE_ID = tr.TARIFF_RANGE_ID
LEFT JOIN UNIT tru ON tr.UNIT_ID = tru.UNIT_ID
LEFT JOIN MEASUREMENT_UNIT trmu ON tr.MEASUREMENT_UNIT_ID = trmu.MEASUREMENT_UNIT_ID
join TARIFF_CUSTOMER tc on t.TARIFF_ID = tc.TARIFF_ID and tc.COMPANY_ID = 516 
--where ti.CODE in ('POIADM2', 'BREDC', 'CHEMADD1', 'LOADRAVAGO', 'NEUTRKOD', 'AOTRHALBM')
--where tf.INTERNAL_COMPANY_ID = 1
where (PERIOD_FROM<getdate() and PERIOD_TO > getdate())
ORDER BY 4
