insert into PRODUCT_SID_SID_VALUE (PRODUCT_SID_ID, PREDEFINED_SID_VALUE_ID) 
select psi.PRODUCT_STORAGE_IDENTIFIER_ID, sipv.STORAGE_IDENTIFIER_PR_VALUE_ID
from  PRODUCT_STORAGE_IDENTIFIER psi, PRODUCT p, STORAGE_IDENTIFIER_PR_VALUE sipv
	where psi.PRODUCT_ID = p.PRODUCT_ID and p.CODE = 'Calcium Nitrate' and psi.SID_ID = sipv.SID_ID 
	and not exists (select * from PRODUCT_SID_SID_VALUE where PRODUCT_SID_ID = psi.PRODUCT_STORAGE_IDENTIFIER_ID and PREDEFINED_SID_VALUE_ID = sipv.STORAGE_IDENTIFIER_PR_VALUE_ID)
	
-- ver 2
insert into PRODUCT_SID_SID_VALUE (PRODUCT_SID_ID, PREDEFINED_SID_VALUE_ID) 
select psi.PRODUCT_STORAGE_IDENTIFIER_ID, sipv.STORAGE_IDENTIFIER_PR_VALUE_ID
from  PRODUCT_STORAGE_IDENTIFIER psi, STORAGE_IDENTIFIER_PR_VALUE sipv
	where psi.PRODUCT_ID in (97, 98) and psi.SID_ID = sipv.SID_ID 
	and not exists (select * from PRODUCT_SID_SID_VALUE where PRODUCT_SID_ID = psi.PRODUCT_STORAGE_IDENTIFIER_ID and PREDEFINED_SID_VALUE_ID = sipv.STORAGE_IDENTIFIER_PR_VALUE_ID)