-- problem PSIs #1
select * from PRODUCT_STORAGE_IDENTIFIER psi join PRODUCT p on psi.PRODUCT_ID = p.PRODUCT_ID
	join PRODUCT_INT_COMPANY pic on p.PRODUCT_ID = pic.PRODUCT_ID
	join PRODUCT_COMPANY pc on p.PRODUCT_ID = pc.PRODUCT_ID
 where psi.SID_ID in (select SID_ID from STORAGE_IDENTIFIER_PR_VALUE)
	and psi.PRODUCT_STORAGE_IDENTIFIER_ID not in (select PRODUCT_SID_ID from PRODUCT_SID_SID_VALUE)
	
-- problem PSIs #2
select * from PRODUCT_STORAGE_IDENTIFIER psi join PRODUCT p on psi.PRODUCT_ID = p.PRODUCT_ID
	join PRODUCT_INT_COMPANY pic on p.PRODUCT_ID = pic.PRODUCT_ID
	join PRODUCT_COMPANY pc on p.PRODUCT_ID = pc.PRODUCT_ID
	left join (select PRODUCT_SID_ID, count(*) as NUM_SID_VALUES from PRODUCT_SID_SID_VALUE group by PRODUCT_SID_ID) pssv on psi.PRODUCT_STORAGE_IDENTIFIER_ID = pssv.PRODUCT_SID_ID
 where psi.SID_ID in (select SID_ID from STORAGE_IDENTIFIER_PR_VALUE) --and NUM_SID_VALUES is null
 order by NUM_SID_VALUES desc
 
-- back-up PSSVs
select * into bak_PSSV from PRODUCT_SID_SID_VALUE

-- insert needed PSSVs
insert into PRODUCT_SID_SID_VALUE (PRODUCT_SID_ID, PREDEFINED_SID_VALUE_ID)
	select psi.PRODUCT_STORAGE_IDENTIFIER_ID, sipv.STORAGE_IDENTIFIER_PR_VALUE_ID
	from PRODUCT_STORAGE_IDENTIFIER psi join STORAGE_IDENTIFIER_PR_VALUE sipv on psi.SID_ID = sipv.SID_ID
	where psi.SID_ID in (select SID_ID from STORAGE_IDENTIFIER_PR_VALUE)
		and psi.PRODUCT_STORAGE_IDENTIFIER_ID not in (select PRODUCT_SID_ID from PRODUCT_SID_SID_VALUE)
		
-- insert PSSVs #2
insert into PRODUCT_SID_SID_VALUE (PRODUCT_SID_ID, PREDEFINED_SID_VALUE_ID)
	select psi.PRODUCT_STORAGE_IDENTIFIER_ID, sipv.STORAGE_IDENTIFIER_PR_VALUE_ID
	from PRODUCT_STORAGE_IDENTIFIER psi join STORAGE_IDENTIFIER_PR_VALUE sipv on psi.SID_ID = sipv.SID_ID
	where psi.SID_ID in (select SID_ID from STORAGE_IDENTIFIER_PR_VALUE) and psi.SID_ID != 13
	and not exists (select 1 from PRODUCT_SID_SID_VALUE pssv1 where pssv1.PRODUCT_SID_ID = psi.PRODUCT_STORAGE_IDENTIFIER_ID
		and pssv1.PREDEFINED_SID_VALUE_ID = sipv.STORAGE_IDENTIFIER_PR_VALUE_ID)
		
insert into PRODUCT_SID_SID_VALUE (PRODUCT_SID_ID, PREDEFINED_SID_VALUE_ID)
	select psi.PRODUCT_STORAGE_IDENTIFIER_ID, 5
	from PRODUCT_STORAGE_IDENTIFIER psi join PRODUCT_INT_COMPANY pic on psi.PRODUCT_ID = pic.PRODUCT_ID and pic.INT_COMPANYNR=246 and psi.SID_ID = 13
	and not exists (select 1 from PRODUCT_SID_SID_VALUE pssv1 where pssv1.PRODUCT_SID_ID = psi.PRODUCT_STORAGE_IDENTIFIER_ID
		and pssv1.PREDEFINED_SID_VALUE_ID = 5)
		
 -- problem PSIs for VMBrasil
select * from PRODUCT_STORAGE_IDENTIFIER psi join PRODUCT p on psi.PRODUCT_ID = p.PRODUCT_ID
	join PRODUCT_INT_COMPANY pic on p.PRODUCT_ID = pic.PRODUCT_ID
	--join PRODUCT_GROUP_PRODUCT pgp on p.PRODUCT_ID = pgp.PRODUCT_ID
	join PRODUCT_COMPANY pc on p.PRODUCT_ID = pc.PRODUCT_ID
	left join (select PRODUCT_SID_ID, count(*) as NUM_SID_VALUES from PRODUCT_SID_SID_VALUE group by PRODUCT_SID_ID) pssv on psi.PRODUCT_STORAGE_IDENTIFIER_ID = pssv.PRODUCT_SID_ID
	--join PRODUCT_SID_SID_VALUE pssv on psi.PRODUCT_STORAGE_IDENTIFIER_ID = pssv.PRODUCT_SID_ID
 where psi.SID_ID in (select SID_ID from STORAGE_IDENTIFIER_PR_VALUE) and NUM_SID_VALUES is null 
 and pic.INT_COMPANYNR = 246 and psi.SID_ID = 13 --and pgp.PRODUCT_GROUP_ID = 8
 --order by pgp.PRODUCT_GROUP_ID

 insert into PRODUCT_SID_SID_VALUE (PRODUCT_SID_ID, PREDEFINED_SID_VALUE_ID)
	select psi.PRODUCT_STORAGE_IDENTIFIER_ID, sipv.STORAGE_IDENTIFIER_PR_VALUE_ID
	from PRODUCT_STORAGE_IDENTIFIER psi join STORAGE_IDENTIFIER_PR_VALUE sipv on psi.SID_ID = sipv.SID_ID
	join PRODUCT_INT_COMPANY pic on psi.PRODUCT_ID = pic.PRODUCT_ID and pic.INT_COMPANYNR = 299
	where psi.SID_ID in (select SID_ID from STORAGE_IDENTIFIER_PR_VALUE) and psi.SID_ID = 13
	and not exists (select 1 from PRODUCT_SID_SID_VALUE pssv1 where pssv1.PRODUCT_SID_ID = psi.PRODUCT_STORAGE_IDENTIFIER_ID
		and pssv1.PREDEFINED_SID_VALUE_ID = sipv.STORAGE_IDENTIFIER_PR_VALUE_ID)
		
-- product sids for VMR that have CS and no values for it at all		
select psi.PRODUCT_STORAGE_IDENTIFIER_ID from PRODUCT_STORAGE_IDENTIFIER psi
	join PRODUCT_INT_COMPANY pic on psi.PRODUCT_ID = pic.PRODUCT_ID and pic.INT_COMPANYNR = 299 and psi.SID_ID=13
	where psi.PRODUCT_STORAGE_IDENTIFIER_ID not in (select PRODUCT_SID_ID from PRODUCT_SID_SID_VALUE )
	
insert into PRODUCT_SID_SID_VALUE (PRODUCT_SID_ID, PREDEFINED_SID_VALUE_ID)
select psi.PRODUCT_STORAGE_IDENTIFIER_ID, sipv.STORAGE_IDENTIFIER_PR_VALUE_ID
from PRODUCT_STORAGE_IDENTIFIER psi, STORAGE_IDENTIFIER_PR_VALUE sipv,
	PRODUCT_INT_COMPANY pic where psi.PRODUCT_ID = pic.PRODUCT_ID and pic.INT_COMPANYNR = 299 and psi.SID_ID=13
	and psi.PRODUCT_STORAGE_IDENTIFIER_ID not in (select PRODUCT_SID_ID from PRODUCT_SID_SID_VALUE )
	and sipv.SID_ID = 13

-- BELGOMILK insert
insert into PRODUCT_SID_SID_VALUE (PRODUCT_SID_ID, PREDEFINED_SID_VALUE_ID)
	select psi.PRODUCT_STORAGE_IDENTIFIER_ID, sipv.STORAGE_IDENTIFIER_PR_VALUE_ID
	from PRODUCT_STORAGE_IDENTIFIER psi join STORAGE_IDENTIFIER_PR_VALUE sipv on psi.SID_ID = sipv.SID_ID
	join PRODUCT_GROUP_PRODUCT pgp on psi.PRODUCT_ID = pgp.PRODUCT_ID join PRODUCT_GROUP pg on pgp.PRODUCT_GROUP_ID = pg.PRODUCT_GROUP_ID and pg.CODE = 'BELGO'
	where psi.SID_ID in (select SID_ID from STORAGE_IDENTIFIER_PR_VALUE) --and psi.SID_ID = 43