declare @LOCATION_MAPPING table (
 OLD_LOCATION_ID int,
 NEW_LOCATION_ID int
);

insert into @LOCATION_MAPPING (OLD_LOCATION_ID, NEW_LOCATION_ID) select lo.LOCATION_ID, ln.LOCATION_ID from LOCATION lo, LOCATION ln where lo.[ADDRESS] = 'HAZ4A1' and ln.[ADDRESS] = 'H4R0010'
insert into @LOCATION_MAPPING (OLD_LOCATION_ID, NEW_LOCATION_ID) select lo.LOCATION_ID, ln.LOCATION_ID from LOCATION lo, LOCATION ln where lo.[ADDRESS] = 'HAZ4A2' and ln.[ADDRESS] = 'H4R0011'
insert into @LOCATION_MAPPING (OLD_LOCATION_ID, NEW_LOCATION_ID) select lo.LOCATION_ID, ln.LOCATION_ID from LOCATION lo, LOCATION ln where lo.[ADDRESS] = 'HAZ4A3' and ln.[ADDRESS] = 'H4R0012'
insert into @LOCATION_MAPPING (OLD_LOCATION_ID, NEW_LOCATION_ID) select lo.LOCATION_ID, ln.LOCATION_ID from LOCATION lo, LOCATION ln where lo.[ADDRESS] = 'HAZ4A4' and ln.[ADDRESS] = 'H4R0013'
insert into @LOCATION_MAPPING (OLD_LOCATION_ID, NEW_LOCATION_ID) select lo.LOCATION_ID, ln.LOCATION_ID from LOCATION lo, LOCATION ln where lo.[ADDRESS] = 'HAZ4A5' and ln.[ADDRESS] = 'H4R0014'
insert into @LOCATION_MAPPING (OLD_LOCATION_ID, NEW_LOCATION_ID) select lo.LOCATION_ID, ln.LOCATION_ID from LOCATION lo, LOCATION ln where lo.[ADDRESS] = 'HAZ4A6' and ln.[ADDRESS] = 'H4R0015'
insert into @LOCATION_MAPPING (OLD_LOCATION_ID, NEW_LOCATION_ID) select lo.LOCATION_ID, ln.LOCATION_ID from LOCATION lo, LOCATION ln where lo.[ADDRESS] = 'HAZ4A7' and ln.[ADDRESS] = 'H4R0020'
insert into @LOCATION_MAPPING (OLD_LOCATION_ID, NEW_LOCATION_ID) select lo.LOCATION_ID, ln.LOCATION_ID from LOCATION lo, LOCATION ln where lo.[ADDRESS] = 'HAZ4A8' and ln.[ADDRESS] = 'H4R0021'
insert into @LOCATION_MAPPING (OLD_LOCATION_ID, NEW_LOCATION_ID) select lo.LOCATION_ID, ln.LOCATION_ID from LOCATION lo, LOCATION ln where lo.[ADDRESS] = 'HAZ4A9' and ln.[ADDRESS] = 'H4R0022'
insert into @LOCATION_MAPPING (OLD_LOCATION_ID, NEW_LOCATION_ID) select lo.LOCATION_ID, ln.LOCATION_ID from LOCATION lo, LOCATION ln where lo.[ADDRESS] = 'HAZ4A10' and ln.[ADDRESS] = 'H4R0023'
insert into @LOCATION_MAPPING (OLD_LOCATION_ID, NEW_LOCATION_ID) select lo.LOCATION_ID, ln.LOCATION_ID from LOCATION lo, LOCATION ln where lo.[ADDRESS] = 'HAZ4A11' and ln.[ADDRESS] = 'H4R0024'
insert into @LOCATION_MAPPING (OLD_LOCATION_ID, NEW_LOCATION_ID) select lo.LOCATION_ID, ln.LOCATION_ID from LOCATION lo, LOCATION ln where lo.[ADDRESS] = 'HAZ4A12' and ln.[ADDRESS] = 'H4R0025'
insert into @LOCATION_MAPPING (OLD_LOCATION_ID, NEW_LOCATION_ID) select lo.LOCATION_ID, ln.LOCATION_ID from LOCATION lo, LOCATION ln where lo.[ADDRESS] = 'HAZ4A13' and ln.[ADDRESS] = 'H4R0030'
insert into @LOCATION_MAPPING (OLD_LOCATION_ID, NEW_LOCATION_ID) select lo.LOCATION_ID, ln.LOCATION_ID from LOCATION lo, LOCATION ln where lo.[ADDRESS] = 'HAZ4A14' and ln.[ADDRESS] = 'H4R0031'
insert into @LOCATION_MAPPING (OLD_LOCATION_ID, NEW_LOCATION_ID) select lo.LOCATION_ID, ln.LOCATION_ID from LOCATION lo, LOCATION ln where lo.[ADDRESS] = 'HAZ4A15' and ln.[ADDRESS] = 'H4R0032'
insert into @LOCATION_MAPPING (OLD_LOCATION_ID, NEW_LOCATION_ID) select lo.LOCATION_ID, ln.LOCATION_ID from LOCATION lo, LOCATION ln where lo.[ADDRESS] = 'HAZ4A16' and ln.[ADDRESS] = 'H4R0033'
insert into @LOCATION_MAPPING (OLD_LOCATION_ID, NEW_LOCATION_ID) select lo.LOCATION_ID, ln.LOCATION_ID from LOCATION lo, LOCATION ln where lo.[ADDRESS] = 'HAZ4A17' and ln.[ADDRESS] = 'H4R0034'
insert into @LOCATION_MAPPING (OLD_LOCATION_ID, NEW_LOCATION_ID) select lo.LOCATION_ID, ln.LOCATION_ID from LOCATION lo, LOCATION ln where lo.[ADDRESS] = 'HAZ4A18' and ln.[ADDRESS] = 'H4R0035'
insert into @LOCATION_MAPPING (OLD_LOCATION_ID, NEW_LOCATION_ID) select lo.LOCATION_ID, ln.LOCATION_ID from LOCATION lo, LOCATION ln where lo.[ADDRESS] = 'HAZ4A19' and ln.[ADDRESS] = 'H4R0040'
insert into @LOCATION_MAPPING (OLD_LOCATION_ID, NEW_LOCATION_ID) select lo.LOCATION_ID, ln.LOCATION_ID from LOCATION lo, LOCATION ln where lo.[ADDRESS] = 'HAZ4A20' and ln.[ADDRESS] = 'H4R0041'
insert into @LOCATION_MAPPING (OLD_LOCATION_ID, NEW_LOCATION_ID) select lo.LOCATION_ID, ln.LOCATION_ID from LOCATION lo, LOCATION ln where lo.[ADDRESS] = 'HAZ4A21' and ln.[ADDRESS] = 'H4R0042'
insert into @LOCATION_MAPPING (OLD_LOCATION_ID, NEW_LOCATION_ID) select lo.LOCATION_ID, ln.LOCATION_ID from LOCATION lo, LOCATION ln where lo.[ADDRESS] = 'HAZ4A22' and ln.[ADDRESS] = 'H4R0043'
insert into @LOCATION_MAPPING (OLD_LOCATION_ID, NEW_LOCATION_ID) select lo.LOCATION_ID, ln.LOCATION_ID from LOCATION lo, LOCATION ln where lo.[ADDRESS] = 'HAZ4A23' and ln.[ADDRESS] = 'H4R0044'
insert into @LOCATION_MAPPING (OLD_LOCATION_ID, NEW_LOCATION_ID) select lo.LOCATION_ID, ln.LOCATION_ID from LOCATION lo, LOCATION ln where lo.[ADDRESS] = 'HAZ4A24' and ln.[ADDRESS] = 'H4R0045'
insert into @LOCATION_MAPPING (OLD_LOCATION_ID, NEW_LOCATION_ID) select lo.LOCATION_ID, ln.LOCATION_ID from LOCATION lo, LOCATION ln where lo.[ADDRESS] = 'HAZ4A25' and ln.[ADDRESS] = 'H4R0050'
insert into @LOCATION_MAPPING (OLD_LOCATION_ID, NEW_LOCATION_ID) select lo.LOCATION_ID, ln.LOCATION_ID from LOCATION lo, LOCATION ln where lo.[ADDRESS] = 'HAZ4A26' and ln.[ADDRESS] = 'H4R0051'
insert into @LOCATION_MAPPING (OLD_LOCATION_ID, NEW_LOCATION_ID) select lo.LOCATION_ID, ln.LOCATION_ID from LOCATION lo, LOCATION ln where lo.[ADDRESS] = 'HAZ4A27' and ln.[ADDRESS] = 'H4R0052'
insert into @LOCATION_MAPPING (OLD_LOCATION_ID, NEW_LOCATION_ID) select lo.LOCATION_ID, ln.LOCATION_ID from LOCATION lo, LOCATION ln where lo.[ADDRESS] = 'HAZ4A28' and ln.[ADDRESS] = 'H4R0053'
insert into @LOCATION_MAPPING (OLD_LOCATION_ID, NEW_LOCATION_ID) select lo.LOCATION_ID, ln.LOCATION_ID from LOCATION lo, LOCATION ln where lo.[ADDRESS] = 'HAZ4A29' and ln.[ADDRESS] = 'H4R0054'
insert into @LOCATION_MAPPING (OLD_LOCATION_ID, NEW_LOCATION_ID) select lo.LOCATION_ID, ln.LOCATION_ID from LOCATION lo, LOCATION ln where lo.[ADDRESS] = 'HAZ4A30' and ln.[ADDRESS] = 'H4R0055'
insert into @LOCATION_MAPPING (OLD_LOCATION_ID, NEW_LOCATION_ID) select lo.LOCATION_ID, ln.LOCATION_ID from LOCATION lo, LOCATION ln where lo.[ADDRESS] = 'HAZ4B1' and ln.[ADDRESS] = 'H4R0060'
insert into @LOCATION_MAPPING (OLD_LOCATION_ID, NEW_LOCATION_ID) select lo.LOCATION_ID, ln.LOCATION_ID from LOCATION lo, LOCATION ln where lo.[ADDRESS] = 'HAZ4B2' and ln.[ADDRESS] = 'H4R0061'
insert into @LOCATION_MAPPING (OLD_LOCATION_ID, NEW_LOCATION_ID) select lo.LOCATION_ID, ln.LOCATION_ID from LOCATION lo, LOCATION ln where lo.[ADDRESS] = 'HAZ4B3' and ln.[ADDRESS] = 'H4R0062'
insert into @LOCATION_MAPPING (OLD_LOCATION_ID, NEW_LOCATION_ID) select lo.LOCATION_ID, ln.LOCATION_ID from LOCATION lo, LOCATION ln where lo.[ADDRESS] = 'HAZ4B4' and ln.[ADDRESS] = 'H4R0063'
insert into @LOCATION_MAPPING (OLD_LOCATION_ID, NEW_LOCATION_ID) select lo.LOCATION_ID, ln.LOCATION_ID from LOCATION lo, LOCATION ln where lo.[ADDRESS] = 'HAZ4B5' and ln.[ADDRESS] = 'H4R0064'
insert into @LOCATION_MAPPING (OLD_LOCATION_ID, NEW_LOCATION_ID) select lo.LOCATION_ID, ln.LOCATION_ID from LOCATION lo, LOCATION ln where lo.[ADDRESS] = 'HAZ4B6' and ln.[ADDRESS] = 'H4R0065'
insert into @LOCATION_MAPPING (OLD_LOCATION_ID, NEW_LOCATION_ID) select lo.LOCATION_ID, ln.LOCATION_ID from LOCATION lo, LOCATION ln where lo.[ADDRESS] = 'HAZ4B7' and ln.[ADDRESS] = 'H4R0070'
insert into @LOCATION_MAPPING (OLD_LOCATION_ID, NEW_LOCATION_ID) select lo.LOCATION_ID, ln.LOCATION_ID from LOCATION lo, LOCATION ln where lo.[ADDRESS] = 'HAZ4B8' and ln.[ADDRESS] = 'H4R0071'
insert into @LOCATION_MAPPING (OLD_LOCATION_ID, NEW_LOCATION_ID) select lo.LOCATION_ID, ln.LOCATION_ID from LOCATION lo, LOCATION ln where lo.[ADDRESS] = 'HAZ4B9' and ln.[ADDRESS] = 'H4R0072'
insert into @LOCATION_MAPPING (OLD_LOCATION_ID, NEW_LOCATION_ID) select lo.LOCATION_ID, ln.LOCATION_ID from LOCATION lo, LOCATION ln where lo.[ADDRESS] = 'HAZ4B10' and ln.[ADDRESS] = 'H4R0073'
insert into @LOCATION_MAPPING (OLD_LOCATION_ID, NEW_LOCATION_ID) select lo.LOCATION_ID, ln.LOCATION_ID from LOCATION lo, LOCATION ln where lo.[ADDRESS] = 'HAZ4B11' and ln.[ADDRESS] = 'H4R0074'
insert into @LOCATION_MAPPING (OLD_LOCATION_ID, NEW_LOCATION_ID) select lo.LOCATION_ID, ln.LOCATION_ID from LOCATION lo, LOCATION ln where lo.[ADDRESS] = 'HAZ4B12' and ln.[ADDRESS] = 'H4R0075'
insert into @LOCATION_MAPPING (OLD_LOCATION_ID, NEW_LOCATION_ID) select lo.LOCATION_ID, ln.LOCATION_ID from LOCATION lo, LOCATION ln where lo.[ADDRESS] = 'HAZ4B13' and ln.[ADDRESS] = 'H4R0080'
insert into @LOCATION_MAPPING (OLD_LOCATION_ID, NEW_LOCATION_ID) select lo.LOCATION_ID, ln.LOCATION_ID from LOCATION lo, LOCATION ln where lo.[ADDRESS] = 'HAZ4B14' and ln.[ADDRESS] = 'H4R0081'
insert into @LOCATION_MAPPING (OLD_LOCATION_ID, NEW_LOCATION_ID) select lo.LOCATION_ID, ln.LOCATION_ID from LOCATION lo, LOCATION ln where lo.[ADDRESS] = 'HAZ4B15' and ln.[ADDRESS] = 'H4R0082'
insert into @LOCATION_MAPPING (OLD_LOCATION_ID, NEW_LOCATION_ID) select lo.LOCATION_ID, ln.LOCATION_ID from LOCATION lo, LOCATION ln where lo.[ADDRESS] = 'HAZ4B16' and ln.[ADDRESS] = 'H4R0083'
insert into @LOCATION_MAPPING (OLD_LOCATION_ID, NEW_LOCATION_ID) select lo.LOCATION_ID, ln.LOCATION_ID from LOCATION lo, LOCATION ln where lo.[ADDRESS] = 'HAZ4B17' and ln.[ADDRESS] = 'H4R0084'
insert into @LOCATION_MAPPING (OLD_LOCATION_ID, NEW_LOCATION_ID) select lo.LOCATION_ID, ln.LOCATION_ID from LOCATION lo, LOCATION ln where lo.[ADDRESS] = 'HAZ4B18' and ln.[ADDRESS] = 'H4R0085'
insert into @LOCATION_MAPPING (OLD_LOCATION_ID, NEW_LOCATION_ID) select lo.LOCATION_ID, ln.LOCATION_ID from LOCATION lo, LOCATION ln where lo.[ADDRESS] = 'HAZ4B19' and ln.[ADDRESS] = 'H4R0090'
insert into @LOCATION_MAPPING (OLD_LOCATION_ID, NEW_LOCATION_ID) select lo.LOCATION_ID, ln.LOCATION_ID from LOCATION lo, LOCATION ln where lo.[ADDRESS] = 'HAZ4B20' and ln.[ADDRESS] = 'H4R0091'
insert into @LOCATION_MAPPING (OLD_LOCATION_ID, NEW_LOCATION_ID) select lo.LOCATION_ID, ln.LOCATION_ID from LOCATION lo, LOCATION ln where lo.[ADDRESS] = 'HAZ4B21' and ln.[ADDRESS] = 'H4R0092'
insert into @LOCATION_MAPPING (OLD_LOCATION_ID, NEW_LOCATION_ID) select lo.LOCATION_ID, ln.LOCATION_ID from LOCATION lo, LOCATION ln where lo.[ADDRESS] = 'HAZ4B22' and ln.[ADDRESS] = 'H4R0093'
insert into @LOCATION_MAPPING (OLD_LOCATION_ID, NEW_LOCATION_ID) select lo.LOCATION_ID, ln.LOCATION_ID from LOCATION lo, LOCATION ln where lo.[ADDRESS] = 'HAZ4B23' and ln.[ADDRESS] = 'H4R0094'
insert into @LOCATION_MAPPING (OLD_LOCATION_ID, NEW_LOCATION_ID) select lo.LOCATION_ID, ln.LOCATION_ID from LOCATION lo, LOCATION ln where lo.[ADDRESS] = 'HAZ4B24' and ln.[ADDRESS] = 'H4R0095'
insert into @LOCATION_MAPPING (OLD_LOCATION_ID, NEW_LOCATION_ID) select lo.LOCATION_ID, ln.LOCATION_ID from LOCATION lo, LOCATION ln where lo.[ADDRESS] = 'HAZ4B25' and ln.[ADDRESS] = 'H4R0100'
insert into @LOCATION_MAPPING (OLD_LOCATION_ID, NEW_LOCATION_ID) select lo.LOCATION_ID, ln.LOCATION_ID from LOCATION lo, LOCATION ln where lo.[ADDRESS] = 'HAZ4B26' and ln.[ADDRESS] = 'H4R0101'
insert into @LOCATION_MAPPING (OLD_LOCATION_ID, NEW_LOCATION_ID) select lo.LOCATION_ID, ln.LOCATION_ID from LOCATION lo, LOCATION ln where lo.[ADDRESS] = 'HAZ4B27' and ln.[ADDRESS] = 'H4R0102'
insert into @LOCATION_MAPPING (OLD_LOCATION_ID, NEW_LOCATION_ID) select lo.LOCATION_ID, ln.LOCATION_ID from LOCATION lo, LOCATION ln where lo.[ADDRESS] = 'HAZ4B28' and ln.[ADDRESS] = 'H4R0103'
insert into @LOCATION_MAPPING (OLD_LOCATION_ID, NEW_LOCATION_ID) select lo.LOCATION_ID, ln.LOCATION_ID from LOCATION lo, LOCATION ln where lo.[ADDRESS] = 'HAZ4B29' and ln.[ADDRESS] = 'H4R0104'
insert into @LOCATION_MAPPING (OLD_LOCATION_ID, NEW_LOCATION_ID) select lo.LOCATION_ID, ln.LOCATION_ID from LOCATION lo, LOCATION ln where lo.[ADDRESS] = 'HAZ4B30' and ln.[ADDRESS] = 'H4R0105'
insert into @LOCATION_MAPPING (OLD_LOCATION_ID, NEW_LOCATION_ID) select lo.LOCATION_ID, ln.LOCATION_ID from LOCATION lo, LOCATION ln where lo.[ADDRESS] = 'HAZ4C1' and ln.[ADDRESS] = 'H4R0110'
insert into @LOCATION_MAPPING (OLD_LOCATION_ID, NEW_LOCATION_ID) select lo.LOCATION_ID, ln.LOCATION_ID from LOCATION lo, LOCATION ln where lo.[ADDRESS] = 'HAZ4C2' and ln.[ADDRESS] = 'H4R0111'
insert into @LOCATION_MAPPING (OLD_LOCATION_ID, NEW_LOCATION_ID) select lo.LOCATION_ID, ln.LOCATION_ID from LOCATION lo, LOCATION ln where lo.[ADDRESS] = 'HAZ4C3' and ln.[ADDRESS] = 'H4R0112'
insert into @LOCATION_MAPPING (OLD_LOCATION_ID, NEW_LOCATION_ID) select lo.LOCATION_ID, ln.LOCATION_ID from LOCATION lo, LOCATION ln where lo.[ADDRESS] = 'HAZ4C4' and ln.[ADDRESS] = 'H4R0113'
insert into @LOCATION_MAPPING (OLD_LOCATION_ID, NEW_LOCATION_ID) select lo.LOCATION_ID, ln.LOCATION_ID from LOCATION lo, LOCATION ln where lo.[ADDRESS] = 'HAZ4C5' and ln.[ADDRESS] = 'H4R0114'
insert into @LOCATION_MAPPING (OLD_LOCATION_ID, NEW_LOCATION_ID) select lo.LOCATION_ID, ln.LOCATION_ID from LOCATION lo, LOCATION ln where lo.[ADDRESS] = 'HAZ4C6' and ln.[ADDRESS] = 'H4R0115'
insert into @LOCATION_MAPPING (OLD_LOCATION_ID, NEW_LOCATION_ID) select lo.LOCATION_ID, ln.LOCATION_ID from LOCATION lo, LOCATION ln where lo.[ADDRESS] = 'HAZ4C7' and ln.[ADDRESS] = 'H4R0120'
insert into @LOCATION_MAPPING (OLD_LOCATION_ID, NEW_LOCATION_ID) select lo.LOCATION_ID, ln.LOCATION_ID from LOCATION lo, LOCATION ln where lo.[ADDRESS] = 'HAZ4C8' and ln.[ADDRESS] = 'H4R0121'
insert into @LOCATION_MAPPING (OLD_LOCATION_ID, NEW_LOCATION_ID) select lo.LOCATION_ID, ln.LOCATION_ID from LOCATION lo, LOCATION ln where lo.[ADDRESS] = 'HAZ4C9' and ln.[ADDRESS] = 'H4R0122'
insert into @LOCATION_MAPPING (OLD_LOCATION_ID, NEW_LOCATION_ID) select lo.LOCATION_ID, ln.LOCATION_ID from LOCATION lo, LOCATION ln where lo.[ADDRESS] = 'HAZ4C10' and ln.[ADDRESS] = 'H4R0123'
insert into @LOCATION_MAPPING (OLD_LOCATION_ID, NEW_LOCATION_ID) select lo.LOCATION_ID, ln.LOCATION_ID from LOCATION lo, LOCATION ln where lo.[ADDRESS] = 'HAZ4C11' and ln.[ADDRESS] = 'H4R0124'
insert into @LOCATION_MAPPING (OLD_LOCATION_ID, NEW_LOCATION_ID) select lo.LOCATION_ID, ln.LOCATION_ID from LOCATION lo, LOCATION ln where lo.[ADDRESS] = 'HAZ4C12' and ln.[ADDRESS] = 'H4R0125'
insert into @LOCATION_MAPPING (OLD_LOCATION_ID, NEW_LOCATION_ID) select lo.LOCATION_ID, ln.LOCATION_ID from LOCATION lo, LOCATION ln where lo.[ADDRESS] = 'HAZ4C13' and ln.[ADDRESS] = 'H4R0130'
insert into @LOCATION_MAPPING (OLD_LOCATION_ID, NEW_LOCATION_ID) select lo.LOCATION_ID, ln.LOCATION_ID from LOCATION lo, LOCATION ln where lo.[ADDRESS] = 'HAZ4C14' and ln.[ADDRESS] = 'H4R0131'
insert into @LOCATION_MAPPING (OLD_LOCATION_ID, NEW_LOCATION_ID) select lo.LOCATION_ID, ln.LOCATION_ID from LOCATION lo, LOCATION ln where lo.[ADDRESS] = 'HAZ4C15' and ln.[ADDRESS] = 'H4R0132'
insert into @LOCATION_MAPPING (OLD_LOCATION_ID, NEW_LOCATION_ID) select lo.LOCATION_ID, ln.LOCATION_ID from LOCATION lo, LOCATION ln where lo.[ADDRESS] = 'HAZ4C16' and ln.[ADDRESS] = 'H4R0133'
insert into @LOCATION_MAPPING (OLD_LOCATION_ID, NEW_LOCATION_ID) select lo.LOCATION_ID, ln.LOCATION_ID from LOCATION lo, LOCATION ln where lo.[ADDRESS] = 'HAZ4C17' and ln.[ADDRESS] = 'H4R0134'
insert into @LOCATION_MAPPING (OLD_LOCATION_ID, NEW_LOCATION_ID) select lo.LOCATION_ID, ln.LOCATION_ID from LOCATION lo, LOCATION ln where lo.[ADDRESS] = 'HAZ4C18' and ln.[ADDRESS] = 'H4R0135'
insert into @LOCATION_MAPPING (OLD_LOCATION_ID, NEW_LOCATION_ID) select lo.LOCATION_ID, ln.LOCATION_ID from LOCATION lo, LOCATION ln where lo.[ADDRESS] = 'HAZ4C19' and ln.[ADDRESS] = 'H4R0140'
insert into @LOCATION_MAPPING (OLD_LOCATION_ID, NEW_LOCATION_ID) select lo.LOCATION_ID, ln.LOCATION_ID from LOCATION lo, LOCATION ln where lo.[ADDRESS] = 'HAZ4C20' and ln.[ADDRESS] = 'H4R0141'
insert into @LOCATION_MAPPING (OLD_LOCATION_ID, NEW_LOCATION_ID) select lo.LOCATION_ID, ln.LOCATION_ID from LOCATION lo, LOCATION ln where lo.[ADDRESS] = 'HAZ4C21' and ln.[ADDRESS] = 'H4R0142'
insert into @LOCATION_MAPPING (OLD_LOCATION_ID, NEW_LOCATION_ID) select lo.LOCATION_ID, ln.LOCATION_ID from LOCATION lo, LOCATION ln where lo.[ADDRESS] = 'HAZ4C22' and ln.[ADDRESS] = 'H4R0143'
insert into @LOCATION_MAPPING (OLD_LOCATION_ID, NEW_LOCATION_ID) select lo.LOCATION_ID, ln.LOCATION_ID from LOCATION lo, LOCATION ln where lo.[ADDRESS] = 'HAZ4C23' and ln.[ADDRESS] = 'H4R0144'
insert into @LOCATION_MAPPING (OLD_LOCATION_ID, NEW_LOCATION_ID) select lo.LOCATION_ID, ln.LOCATION_ID from LOCATION lo, LOCATION ln where lo.[ADDRESS] = 'HAZ4C24' and ln.[ADDRESS] = 'H4R0145'
insert into @LOCATION_MAPPING (OLD_LOCATION_ID, NEW_LOCATION_ID) select lo.LOCATION_ID, ln.LOCATION_ID from LOCATION lo, LOCATION ln where lo.[ADDRESS] = 'HAZ4C25' and ln.[ADDRESS] = 'H4R0150'
insert into @LOCATION_MAPPING (OLD_LOCATION_ID, NEW_LOCATION_ID) select lo.LOCATION_ID, ln.LOCATION_ID from LOCATION lo, LOCATION ln where lo.[ADDRESS] = 'HAZ4C26' and ln.[ADDRESS] = 'H4R0151'
insert into @LOCATION_MAPPING (OLD_LOCATION_ID, NEW_LOCATION_ID) select lo.LOCATION_ID, ln.LOCATION_ID from LOCATION lo, LOCATION ln where lo.[ADDRESS] = 'HAZ4C27' and ln.[ADDRESS] = 'H4R0152'
insert into @LOCATION_MAPPING (OLD_LOCATION_ID, NEW_LOCATION_ID) select lo.LOCATION_ID, ln.LOCATION_ID from LOCATION lo, LOCATION ln where lo.[ADDRESS] = 'HAZ4C28' and ln.[ADDRESS] = 'H4R0153'
insert into @LOCATION_MAPPING (OLD_LOCATION_ID, NEW_LOCATION_ID) select lo.LOCATION_ID, ln.LOCATION_ID from LOCATION lo, LOCATION ln where lo.[ADDRESS] = 'HAZ4C29' and ln.[ADDRESS] = 'H4R0154'
insert into @LOCATION_MAPPING (OLD_LOCATION_ID, NEW_LOCATION_ID) select lo.LOCATION_ID, ln.LOCATION_ID from LOCATION lo, LOCATION ln where lo.[ADDRESS] = 'HAZ4C30' and ln.[ADDRESS] = 'H4R0155'
insert into @LOCATION_MAPPING (OLD_LOCATION_ID, NEW_LOCATION_ID) select lo.LOCATION_ID, ln.LOCATION_ID from LOCATION lo, LOCATION ln where lo.[ADDRESS] = 'HAZ4D1' and ln.[ADDRESS] = 'H4R0160'
insert into @LOCATION_MAPPING (OLD_LOCATION_ID, NEW_LOCATION_ID) select lo.LOCATION_ID, ln.LOCATION_ID from LOCATION lo, LOCATION ln where lo.[ADDRESS] = 'HAZ4D2' and ln.[ADDRESS] = 'H4R0161'
insert into @LOCATION_MAPPING (OLD_LOCATION_ID, NEW_LOCATION_ID) select lo.LOCATION_ID, ln.LOCATION_ID from LOCATION lo, LOCATION ln where lo.[ADDRESS] = 'HAZ4D3' and ln.[ADDRESS] = 'H4R0162'
insert into @LOCATION_MAPPING (OLD_LOCATION_ID, NEW_LOCATION_ID) select lo.LOCATION_ID, ln.LOCATION_ID from LOCATION lo, LOCATION ln where lo.[ADDRESS] = 'HAZ4D4' and ln.[ADDRESS] = 'H4R0163'
insert into @LOCATION_MAPPING (OLD_LOCATION_ID, NEW_LOCATION_ID) select lo.LOCATION_ID, ln.LOCATION_ID from LOCATION lo, LOCATION ln where lo.[ADDRESS] = 'HAZ4D5' and ln.[ADDRESS] = 'H4R0164'
insert into @LOCATION_MAPPING (OLD_LOCATION_ID, NEW_LOCATION_ID) select lo.LOCATION_ID, ln.LOCATION_ID from LOCATION lo, LOCATION ln where lo.[ADDRESS] = 'HAZ4D6' and ln.[ADDRESS] = 'H4R0165'
insert into @LOCATION_MAPPING (OLD_LOCATION_ID, NEW_LOCATION_ID) select lo.LOCATION_ID, ln.LOCATION_ID from LOCATION lo, LOCATION ln where lo.[ADDRESS] = 'HAZ4D7' and ln.[ADDRESS] = 'H4R0170'
insert into @LOCATION_MAPPING (OLD_LOCATION_ID, NEW_LOCATION_ID) select lo.LOCATION_ID, ln.LOCATION_ID from LOCATION lo, LOCATION ln where lo.[ADDRESS] = 'HAZ4D8' and ln.[ADDRESS] = 'H4R0171'
insert into @LOCATION_MAPPING (OLD_LOCATION_ID, NEW_LOCATION_ID) select lo.LOCATION_ID, ln.LOCATION_ID from LOCATION lo, LOCATION ln where lo.[ADDRESS] = 'HAZ4D9' and ln.[ADDRESS] = 'H4R0172'
insert into @LOCATION_MAPPING (OLD_LOCATION_ID, NEW_LOCATION_ID) select lo.LOCATION_ID, ln.LOCATION_ID from LOCATION lo, LOCATION ln where lo.[ADDRESS] = 'HAZ4D10' and ln.[ADDRESS] = 'H4R0173'
insert into @LOCATION_MAPPING (OLD_LOCATION_ID, NEW_LOCATION_ID) select lo.LOCATION_ID, ln.LOCATION_ID from LOCATION lo, LOCATION ln where lo.[ADDRESS] = 'HAZ4D11' and ln.[ADDRESS] = 'H4R0174'
insert into @LOCATION_MAPPING (OLD_LOCATION_ID, NEW_LOCATION_ID) select lo.LOCATION_ID, ln.LOCATION_ID from LOCATION lo, LOCATION ln where lo.[ADDRESS] = 'HAZ4D12' and ln.[ADDRESS] = 'H4R0175'
insert into @LOCATION_MAPPING (OLD_LOCATION_ID, NEW_LOCATION_ID) select lo.LOCATION_ID, ln.LOCATION_ID from LOCATION lo, LOCATION ln where lo.[ADDRESS] = 'HAZ4D13' and ln.[ADDRESS] = 'H4R0180'
insert into @LOCATION_MAPPING (OLD_LOCATION_ID, NEW_LOCATION_ID) select lo.LOCATION_ID, ln.LOCATION_ID from LOCATION lo, LOCATION ln where lo.[ADDRESS] = 'HAZ4D14' and ln.[ADDRESS] = 'H4R0181'
insert into @LOCATION_MAPPING (OLD_LOCATION_ID, NEW_LOCATION_ID) select lo.LOCATION_ID, ln.LOCATION_ID from LOCATION lo, LOCATION ln where lo.[ADDRESS] = 'HAZ4D15' and ln.[ADDRESS] = 'H4R0182'
insert into @LOCATION_MAPPING (OLD_LOCATION_ID, NEW_LOCATION_ID) select lo.LOCATION_ID, ln.LOCATION_ID from LOCATION lo, LOCATION ln where lo.[ADDRESS] = 'HAZ4D16' and ln.[ADDRESS] = 'H4R0183'
insert into @LOCATION_MAPPING (OLD_LOCATION_ID, NEW_LOCATION_ID) select lo.LOCATION_ID, ln.LOCATION_ID from LOCATION lo, LOCATION ln where lo.[ADDRESS] = 'HAZ4D17' and ln.[ADDRESS] = 'H4R0184'
insert into @LOCATION_MAPPING (OLD_LOCATION_ID, NEW_LOCATION_ID) select lo.LOCATION_ID, ln.LOCATION_ID from LOCATION lo, LOCATION ln where lo.[ADDRESS] = 'HAZ4D18' and ln.[ADDRESS] = 'H4R0185'
insert into @LOCATION_MAPPING (OLD_LOCATION_ID, NEW_LOCATION_ID) select lo.LOCATION_ID, ln.LOCATION_ID from LOCATION lo, LOCATION ln where lo.[ADDRESS] = 'HAZ4D19' and ln.[ADDRESS] = 'H4R0190'
insert into @LOCATION_MAPPING (OLD_LOCATION_ID, NEW_LOCATION_ID) select lo.LOCATION_ID, ln.LOCATION_ID from LOCATION lo, LOCATION ln where lo.[ADDRESS] = 'HAZ4D20' and ln.[ADDRESS] = 'H4R0191'
insert into @LOCATION_MAPPING (OLD_LOCATION_ID, NEW_LOCATION_ID) select lo.LOCATION_ID, ln.LOCATION_ID from LOCATION lo, LOCATION ln where lo.[ADDRESS] = 'HAZ4D21' and ln.[ADDRESS] = 'H4R0192'
insert into @LOCATION_MAPPING (OLD_LOCATION_ID, NEW_LOCATION_ID) select lo.LOCATION_ID, ln.LOCATION_ID from LOCATION lo, LOCATION ln where lo.[ADDRESS] = 'HAZ4D22' and ln.[ADDRESS] = 'H4R0193'
insert into @LOCATION_MAPPING (OLD_LOCATION_ID, NEW_LOCATION_ID) select lo.LOCATION_ID, ln.LOCATION_ID from LOCATION lo, LOCATION ln where lo.[ADDRESS] = 'HAZ4D23' and ln.[ADDRESS] = 'H4R0194'
insert into @LOCATION_MAPPING (OLD_LOCATION_ID, NEW_LOCATION_ID) select lo.LOCATION_ID, ln.LOCATION_ID from LOCATION lo, LOCATION ln where lo.[ADDRESS] = 'HAZ4D24' and ln.[ADDRESS] = 'H4R0195'
insert into @LOCATION_MAPPING (OLD_LOCATION_ID, NEW_LOCATION_ID) select lo.LOCATION_ID, ln.LOCATION_ID from LOCATION lo, LOCATION ln where lo.[ADDRESS] = 'HAZ4D25' and ln.[ADDRESS] = 'H4R0200'
insert into @LOCATION_MAPPING (OLD_LOCATION_ID, NEW_LOCATION_ID) select lo.LOCATION_ID, ln.LOCATION_ID from LOCATION lo, LOCATION ln where lo.[ADDRESS] = 'HAZ4D26' and ln.[ADDRESS] = 'H4R0201'
insert into @LOCATION_MAPPING (OLD_LOCATION_ID, NEW_LOCATION_ID) select lo.LOCATION_ID, ln.LOCATION_ID from LOCATION lo, LOCATION ln where lo.[ADDRESS] = 'HAZ4D27' and ln.[ADDRESS] = 'H4R0202'
insert into @LOCATION_MAPPING (OLD_LOCATION_ID, NEW_LOCATION_ID) select lo.LOCATION_ID, ln.LOCATION_ID from LOCATION lo, LOCATION ln where lo.[ADDRESS] = 'HAZ4D28' and ln.[ADDRESS] = 'H4R0203'
insert into @LOCATION_MAPPING (OLD_LOCATION_ID, NEW_LOCATION_ID) select lo.LOCATION_ID, ln.LOCATION_ID from LOCATION lo, LOCATION ln where lo.[ADDRESS] = 'HAZ4D29' and ln.[ADDRESS] = 'H4R0204'
insert into @LOCATION_MAPPING (OLD_LOCATION_ID, NEW_LOCATION_ID) select lo.LOCATION_ID, ln.LOCATION_ID from LOCATION lo, LOCATION ln where lo.[ADDRESS] = 'HAZ4D30' and ln.[ADDRESS] = 'H4R0205'

declare @updatedIds table(STOCK_INFO_CONFIG_ID int, LOADING_ORDER_ITEM_ID int, DISCHARGING_ORDER_ITEM_ID int, OPERATION_CONTEXT_ID int);

update sic set
	LOCATION_ID = lm.NEW_LOCATION_ID
OUTPUT INSERTED.STOCK_INFO_CONFIG_ID INTO @updatedIds(STOCK_INFO_CONFIG_ID)
from STOCK_INFO_CONFIG sic
	join @LOCATION_MAPPING lm on sic.LOCATION_ID = lm.OLD_LOCATION_ID
	
update loi SET
	LOCATION_ID = lm.NEW_LOCATION_ID
OUTPUT INSERTED.LOADING_ORDER_ITEM_ID INTO @updatedIds(LOADING_ORDER_ITEM_ID)
from LOADING_ORDER_ITEM loi
	join @LOCATION_MAPPING lm on loi.LOCATION_ID = lm.OLD_LOCATION_ID

update doi SET
	LOCATION_ID = lm.NEW_LOCATION_ID
OUTPUT INSERTED.DISCHARGING_ORDER_ITEM_ID INTO @updatedIds(DISCHARGING_ORDER_ITEM_ID)
from DISCHARGING_ORDER_ITEM doi
	join @LOCATION_MAPPING lm on doi.LOCATION_ID = lm.OLD_LOCATION_ID

update oc
	SET LOCATION_ID = lm.NEW_LOCATION_ID
	OUTPUT INSERTED.OPERATION_CONTEXT_ID INTO @updatedIds(OPERATION_CONTEXT_ID)
	from OPERATION_CONTEXT oc
	join @LOCATION_MAPPING lm on oc.LOCATION_ID = lm.OLD_LOCATION_ID
	
select * from @updatedIds