alter table dbo.COMPANY
 add constraint FK_COMPANY_ADDRESS
 foreign key ([MAIN_ADDRESS_ID])
 references dbo.CRM_ADDRESS (ADDRESS_ID)
go

alter table dbo.[CONFIG_SETTING_VALUE]
 add constraint FK_CONFSETTINGVALUE_IC
 foreign key ([INTERNAL_COMPANYNR])
 references dbo.COMPANY (COMPANYNR)
go

ALTER TABLE [dbo].[EFA_CONTRACTS_LIST]
    ADD CONSTRAINT [PK_EFA_CONTRACTS_LIST] PRIMARY KEY CLUSTERED ([EFA_CONTRACT_ID] ASC);
GO

ALTER TABLE [dbo].[COMPANY] WITH NOCHECK
    ADD CONSTRAINT [FK_COMPANY_MAIN_ADDRESS] FOREIGN KEY ([MAIN_ADDRESS_ID]) REFERENCES [dbo].[CRM_ADDRESS] ([ADDRESS_ID]);
GO