update o set
	INTERNAL_COMPANY_ID = oper.INTERNAL_COMPANY_ID,
	UPDATE_USER = 'la161025',
	UPDATE_TIMESTAMP = GETDATE()
from ORDERS o
	join ORDER_ITEM oi on oi.ORDER_ID = o.ORDER_ID
	join OPERATION oper on oi.OPERATION_ID = oper.OPERATION_ID
where o.INTERNAL_COMPANY_ID != oper.INTERNAL_COMPANY_ID
and o.ORDER_ID < 20000