--select * from COMPANY where CODE like 'F%'

select distinct op.ORDER_ITEM_ID from STOCK_INFO si join STOCK_INFO_CONFIG sic on si.STOCK_INFO_CONFIG_ID = sic.STOCK_INFO_CONFIG_ID and sic.OWNER_ID = 559 and sic.ITEM_NUMBER is null
--	join LOADING_OPERATION_REPORT lor on lor.REPORTED_ID = si.STOCK_INFO_ID
--	join DISCHARGING_OPERATION_REPORT dor on dor.REPORTED_ID = si.STOCK_INFO_ID
--	join DISCHARGING_ORDER_ITEM_GOODS doig on doig.STOCK_INFO_ID = si.STOCK_INFO_ID
--	join LOADING_ORDER_ITEM_GOOD loig on loig.STOCK_INFO_ID = si.STOCK_INFO_ID
join LOADING_OPERATION_PLAN lop on si.STOCK_INFO_ID in (lop.PLANNED_ID) --, lop.REMAINING_ID) --, lop.ORDERED_ID, lop.PENDING_ID)
	join OPERATION_PLAN op on lop.LOADING_OPERATION_PLAN_ID = op.OPERATION_PLAN_ID order by 1

select distinct loig.LOADING_ORDER_ITEM_ID from STOCK_INFO si join STOCK_INFO_CONFIG sic on si.STOCK_INFO_CONFIG_ID = sic.STOCK_INFO_CONFIG_ID and sic.OWNER_ID = 559 and sic.ITEM_NUMBER is null
	--join LOADING_OPERATION_REPORT lor on lor.REPORTED_ID = si.STOCK_INFO_ID
	--	join OPERATION_REPORT rpt on lor.LOADING_OPERATION_REPORT_ID = rpt.OPERATION_REPORT_ID order by 1
--	join DISCHARGING_OPERATION_REPORT dor on dor.REPORTED_ID = si.STOCK_INFO_ID
--	join DISCHARGING_ORDER_ITEM_GOODS doig on doig.STOCK_INFO_ID = si.STOCK_INFO_ID
	join LOADING_ORDER_ITEM_GOOD loig on loig.STOCK_INFO_ID = si.STOCK_INFO_ID order by 1
--join LOADING_OPERATION_PLAN lop on si.STOCK_INFO_ID in (lop.PENDING_ID) --, lop.ORDERED_ID, lop.PENDING_ID)
--	join OPERATION_PLAN op on lop.LOADING_OPERATION_PLAN_ID = op.OPERATION_PLAN_ID order by 1

select distinct S.*, sic.STOCK_INFO_CONFIG_ID, sic.PRODUCT_ID from STOCK_INFO si join STOCK_INFO_CONFIG sic on si.STOCK_INFO_CONFIG_ID = sic.STOCK_INFO_CONFIG_ID and sic.OWNER_ID = 559 and sic.ITEM_NUMBER is null
join
(select STOCK_INFO_ID, LOADING_ORDER_ITEM_ID as ORDER_ITEM_ID, 'LOIG' as TYPE from LOADING_ORDER_ITEM_GOOD
union
select STOCK_INFO_ID, DISCHARGING_ORDER_ITEM_ID, 'DOIG' from DISCHARGING_ORDER_ITEM_GOODS 
union
select REPORTED_ID, rpt.ORDER_ITEM_ID, 'LOR' from LOADING_OPERATION_REPORT lor join OPERATION_REPORT rpt on lor.LOADING_OPERATION_REPORT_ID = rpt.OPERATION_REPORT_ID
union
select REPORTED_ID, rpt2.ORDER_ITEM_ID, 'DOR' from DISCHARGING_OPERATION_REPORT dor join OPERATION_REPORT rpt2 on dor.DISCHARGING_OPERATION_REPORT_ID = rpt2.OPERATION_REPORT_ID
union
select PLANNED_ID, op.ORDER_ITEM_ID, 'PLAN' from LOADING_OPERATION_PLAN lop join OPERATION_PLAN op on lop.LOADING_OPERATION_PLAN_ID = op.OPERATION_PLAN_ID
union
select PLANNED_ID, op2.ORDER_ITEM_ID, 'PL2' from DISCHARGING_OPERATION_PLAN dop join OPERATION_PLAN op2 on dop.DISCHARGING_OPERATION_PLAN_ID = op2.OPERATION_PLAN_ID 
) S on si.STOCK_INFO_ID = S.STOCK_INFO_ID order by 2


select distinct S.ORDER_ITEM_ID from STOCK_INFO si join STOCK_INFO_CONFIG sic on si.STOCK_INFO_CONFIG_ID = sic.STOCK_INFO_CONFIG_ID and sic.OWNER_ID = 559 and sic.ITEM_NUMBER is null
join
(select STOCK_INFO_ID, LOADING_ORDER_ITEM_ID as ORDER_ITEM_ID, 'LOIG' as TYPE from LOADING_ORDER_ITEM_GOOD
union
select STOCK_INFO_ID, DISCHARGING_ORDER_ITEM_ID, 'DOIG' from DISCHARGING_ORDER_ITEM_GOODS 
--union
--select REPORTED_ID, rpt.ORDER_ITEM_ID, 'LOR' from LOADING_OPERATION_REPORT lor join OPERATION_REPORT rpt on lor.LOADING_OPERATION_REPORT_ID = rpt.OPERATION_REPORT_ID
--union
--select REPORTED_ID, rpt2.ORDER_ITEM_ID, 'DOR' from DISCHARGING_OPERATION_REPORT dor join OPERATION_REPORT rpt2 on dor.DISCHARGING_OPERATION_REPORT_ID = rpt2.OPERATION_REPORT_ID
--union
--select PLANNED_ID, op.ORDER_ITEM_ID, 'PLAN' from LOADING_OPERATION_PLAN lop join OPERATION_PLAN op on lop.LOADING_OPERATION_PLAN_ID = op.OPERATION_PLAN_ID
--union
--select PLANNED_ID, op2.ORDER_ITEM_ID, 'PL2' from DISCHARGING_OPERATION_PLAN dop join OPERATION_PLAN op2 on dop.DISCHARGING_OPERATION_PLAN_ID = op2.OPERATION_PLAN_ID 
) S on si.STOCK_INFO_ID = S.STOCK_INFO_ID order by 1

select oi.ORDER_ITEM_ID, CAST(oi.ORDER_ID as varchar) + '/' + CAST(oi.SEQUENCE as VARCHAR) as ORDER_ITEM , S.TYPE, oi.EXTERNAL_ID,
	case oi.STATUS when 0 then 'OPEN' when 1 then 'APPROVED' when 2 then 'IN-PROCESS' when 3 then 'COMPLETED' when 4 then 'CLOSED' when 5 then 'CANCELLED' end 'STATUS',
	p.CODE, p.SHORT_DESC, sic.INVENTORY_NUMBER, si.STOCK_INFO_ID, sic.STOCK_INFO_CONFIG_ID
from STOCK_INFO si join STOCK_INFO_CONFIG sic on si.STOCK_INFO_CONFIG_ID = sic.STOCK_INFO_CONFIG_ID and sic.OWNER_ID = 559 and sic.ITEM_NUMBER is null
join
(select STOCK_INFO_ID, LOADING_ORDER_ITEM_ID as ORDER_ITEM_ID, 'LOAD' as TYPE from LOADING_ORDER_ITEM_GOOD
union
select STOCK_INFO_ID, DISCHARGING_ORDER_ITEM_ID, 'DISCH' from DISCHARGING_ORDER_ITEM_GOODS  
) S on si.STOCK_INFO_ID = S.STOCK_INFO_ID
join ORDER_ITEM oi on S.ORDER_ITEM_ID = oi.ORDER_ITEM_ID
join PRODUCT p on sic.PRODUCT_ID = p.PRODUCT_ID
 order by 1