select distinct o.ORDER_ID, o.DATE from ORDER_ITEM oi join ORDERS o on oi.ORDER_ID = o.ORDER_ID and (o.STATUS<2 or oi.STATUS<3)
	--and o.[DATE] < '2017-JAN-1'
and o.ORDER_ID not in (
	select ORDER_ID from ORDER_ITEM oi join (
		select DISCHARGING_ORDER_ITEM_ID, 'D STOCK_INFO_ID', STOCK_INFO_ID from DISCHARGING_ORDER_ITEM_GOODS
		union
		select LOADING_ORDER_ITEM_ID, 'L STOCK_INFO_ID', STOCK_INFO_ID from LOADING_ORDER_ITEM_GOOD
		union
		select STOCK_CHANGE_ORDER_ITEM_ID, 'SC ITEM ID', STOCK_CHANGE_ITEM_ID from STOCK_CHANGE_ORDER_ITEM_GOOD
		union
		select VAS_ORDER_ITEM_ID, 'VAS ITEM ID', VAS_ITEM_ID from VAS_ORDER_ITEM_GOOD
	) as xoi (ORDER_ITEM_ID, INFO, ID) on oi.ORDER_ITEM_ID = xoi.ORDER_ITEM_ID
) order by 1