SELECT	
		r.[OPERATION_REPORT_ID],
		oc.[DATE] as REPORT_DATE,
		case r.[STATUS] when 0 then 'Open' when 1 then 'Processing' when 2 then 'Completed' when 3 then 'Closed' end REPORT_STATUS,
		ist.Direction,
		p.SHORT_DESC,
		p.CODE,
		--ist.INVENTORY_STATUS,
		
		--oc.[SHIFT_ID],
		--oc.[START_TIME],
		--oc.[END_TIME],		
		--r.CREATE_USER as REPORT_USER,	

		--Order
		--ord.ORDER_ID,
		ord.[NUMBER] AS ORDER_NUMBER,
		--ord.[DATE] as ORDER_DATE,
		--c.[NAME] as CUSTOMER,
		--c.[COMPANY_ID] AS CUSTOMER_ID,
		--ord.[EXTERNAL_ID] as ORDER_EXTERNAL_ID,
		--ord.[DESCRIPTION] as ORDER_DESCRIPTION,
		--ord.[STATUS] as ORDER_STATUS,

		--Order Item
		--oi.[ORDER_ITEM_ID],
		oi.[SEQUENCE] as ORDER_ITEM_SEQUENCE,
		oi.[EXTERNAL_ID] as ORDER_ITEM_EXTERNAL_ID,
		--oi.[DESCRIPTION] as ORDER_ITEM_DESCRIPTION,
		--oi.[PLANNED_DATE] as ORDER_ITEM_PLANNED_DATE,
		--oi.[CLOSING_DATE] as ORDER_ITEM_CLOSING_DATE,
		--oi.[COST_CENTRE_ID],
		--oi.[PRIORITY] as ORDER_ITEM_PRIORITY,
		--oi.[STATUS] as ORDER_ITEM_STATUS
		--sic.PRODUCT_ID,
		sic.LOT,
		sic.DATE_IN,
		bsiq.QUANTITY as BU_QTY,
		bu.DESCRIPTION BU,
		ssiq.QUANTITY as SU_QTY,
		su.DESCRIPTION SU,
		nQty.QUANTITY Net,
		sqMtrQty.QUANTITY Sqmtr

		FROM OPERATION_REPORT r 
			--inner join OPERATION o on r.OPERATION_ID = o.OPERATION_ID 
			inner join OPERATION_CONTEXT oc on r.CONTEXT_ID = oc.OPERATION_CONTEXT_ID 
			--left outer join INTERNAL_COMPANY ic on o.INTERNAL_COMPANY_ID = ic.[COMPANY_ID] 
			--left outer join OPERATION_TYPE ot on o.[TYPE_ID] = ot.OPERATION_TYPE_ID 
			left join ORDER_ITEM oi on r.ORDER_ITEM_ID = oi.ORDER_ITEM_ID 
			left join ORDERS ord on oi.ORDER_ID = ord.ORDER_ID 
			--left outer join COMPANY c on ord.CUSTOMER_ID = c.COMPANY_ID	
			join (
				SELECT DISCHARGING_OPERATION_REPORT_ID AS OPERATION_REPORT_ID, 'IN' as Direction, INVENTORY_STATUS, si.STOCK_INFO_ID
					FROM DISCHARGING_OPERATION_REPORT dor join STOCK_INFO si on dor.REPORTED_ID = si.STOCK_INFO_ID
				UNION ALL SELECT LOADING_OPERATION_REPORT_ID AS OPERATION_REPORT_ID, 'OUT', INVENTORY_STATUS , si.STOCK_INFO_ID
					FROM LOADING_OPERATION_REPORT AS lor join STOCK_INFO si on lor.REPORTED_ID = si.STOCK_INFO_ID
				--UNION ALL SELECT STOCK_CHANGE_OPERATION_REPORT_ID AS OPERATION_REPORT_ID, 'Stock Change', INVENTORY_STATUS 
				--	FROM STOCK_CHANGE_OPERATION_REPORT AS scor
		 	--	UNION ALL SELECT VAS_OPERATION_REPORT_ID AS OPERATION_REPORT_ID, 'VAS', INVENTORY_STATUS 
				--	FROM VAS_OPERATION_REPORT
			) AS ist ON r.OPERATION_REPORT_ID = ist.OPERATION_REPORT_ID
			join STOCK_INFO si on ist.STOCK_INFO_ID = si.STOCK_INFO_ID
			join STOCK_INFO_CONFIG sic on si.STOCK_INFO_CONFIG_ID = sic.STOCK_INFO_CONFIG_ID
			join STOCK_INFO_QUANTITY bsiq on si.BASE_QUANTITY_ID = bsiq.STOCK_INFO_QUANTITY_ID
			join UNIT bu on bsiq.UNIT_ID = bu.UNIT_ID
			join PRODUCT p on sic.PRODUCT_ID = p.PRODUCT_ID
			left join STOCK_INFO_QUANTITY ssiq on si.STORAGE_QUANTITY_ID = ssiq.STOCK_INFO_QUANTITY_ID
			left join UNIT su on ssiq.UNIT_ID = su.UNIT_ID
			join (select siqn.QUANTITY, sieq.STOCK_INFO_ID
				from STOCK_INFO_EXTRA_QUANTITY sieq join STOCK_INFO_QUANTITY siqn on sieq.STOCK_INFO_QUANTITY_ID = siqn.STOCK_INFO_QUANTITY_ID
				 and siqn.UNIT_ID = 5) nQty on nQty.STOCK_INFO_ID = si.STOCK_INFO_ID
			join (select siqn.QUANTITY, sieq.STOCK_INFO_ID
				from STOCK_INFO_EXTRA_QUANTITY sieq join STOCK_INFO_QUANTITY siqn on sieq.STOCK_INFO_QUANTITY_ID = siqn.STOCK_INFO_QUANTITY_ID
				 and siqn.UNIT_ID = 11) sqMtrQty on sqMtrQty.STOCK_INFO_ID = si.STOCK_INFO_ID
			--join STOCK_INFO_QUANTITY siqs on sieq.STOCK_INFO_QUANTITY_ID = siqs.STOCK_INFO_QUANTITY_ID and siqs.UNIT_ID = 11

where ord.INTERNAL_COMPANY_ID = 220 and oc.DATE between '1-JAN-2018' and '31-MAR-2018'