CREATE PROCEDURE [dbo].[MakeLocation]
	@Address nvarchar(20),
	@Code nvarchar(15),
	@ParentAddress nvarchar(20),
	@IcCompanyCodes nvarchar(200)	
AS
	declare @LocationId int
	declare @ParentId int
	declare @HierarchiLevel int = 0
	declare @Path nvarchar(250)
	declare @PlainPath nvarchar(250)
	DECLARE @errMsg nvarchar(500)	
BEGIN

	if exists (select 1 from [LOCATION] where ADDRESS = @Address) return
	
	select
		@ParentId = LOCATION_ID,
		@HierarchiLevel = HIERARCHY_LEVEL + 1,
		@PlainPath = IsNull([PLAIN_PATH],'|') + CODE +'|',
		@Path = IsNull([PATH],'|') + cast(LOCATION_ID as nvarchar(20)) + '|'
	from
		LOCATION
	where
		[ADDRESS] = @ParentAddress

	INSERT INTO [dbo].[LOCATION]
			([CODE]
			,[ADDRESS]
			,[STATUS]
			,[HAS_CHILDREN]
			,[HIERARCHY_LEVEL]
			,[PARENT_ID]
			,[PATH]
			,[PLAIN_PATH]
			,[CREATE_USER]
			,[CREATE_TIMESTAMP]
			,[UPDATE_USER]
			,[UPDATE_TIMESTAMP])
	 VALUES
		   (@Code
		   ,@Address
		   ,0
		   ,0
		   ,@HierarchiLevel
		   ,@ParentId
		   ,@Path
		   ,@PlainPath
		   ,'sys170217'
		   ,getdate()
		   ,'sys170217'
		   ,getdate())

	select @LocationId = SCOPE_IDENTITY();		   
		   
	-- Update parent's "HasChildren" property
	UPDATE LOCATION
	SET HAS_CHILDREN = 1
	WHERE LOCATION_ID IN
	(
		SELECT PARENT_ID FROM LOCATION
		WHERE STATUS = 0 AND PARENT_ID IS NOT NULL AND PARENT_ID = @ParentId
		GROUP BY PARENT_ID
	)
	
	--Insert locaiton for all internal companies
	IF @IcCompanyCodes IS NOT NULL
	BEGIN
				 
		DECLARE @pos INT
		DECLARE @len INT
		DECLARE @value NVARCHAR(50)
		
		SET @pos = 0
		SET @len = 0
		SET @IcCompanyCodes = @IcCompanyCodes + ','
		
		WHILE CHARINDEX(',', @IcCompanyCodes, @pos+1)>0
		BEGIN
			SET @len = CHARINDEX(',', @IcCompanyCodes, @pos+1) - @pos
			SET @value = SUBSTRING(@IcCompanyCodes, @pos, @len)

			--Check if the company exists
			IF NOT EXISTS (SELECT * FROM [dbo].[COMPANY] WHERE [CODE] = @value)
			BEGIN
				;select @errMsg = 'Company with code ' + @value +' does not exist. Could not insert location.'
				;THROW 51000, @errMsg, 1;
			END

			INSERT INTO [dbo].[LOCATION_INTERNAL_COMPANY]
				([LOCATION_ID]
				,[INTERNAL_COMPANY_ID])
			SELECT
				@LocationId,
				[COMPANY_ID]
			FROM [dbo].[COMPANY] WHERE [CODE] = @value;

			SET @pos = CHARINDEX(',', @IcCompanyCodes, @pos+@len) + 1

		END		
		
	END	

END
go

set nocount on

exec MakeLocation 'BR5U', 'U','BR5', 'IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5V', 'V','BR5', 'IC_SGN,IC_VMHZP'

exec MakeLocation 'BR5A01', '01','BR5A', 'IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5A47', '47','BR5A', 'IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5A48', '48','BR5A', 'IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5A49', '49','BR5A', 'IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5A50', '50','BR5A', 'IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5A51', '51','BR5A', 'IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5B47', '47','BR5B', 'IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5B48', '48','BR5B', 'IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5B49', '49','BR5B', 'IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5B50', '50','BR5B', 'IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5B51', '51','BR5B', 'IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5C47', '47','BR5C', 'IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5C48', '48','BR5C', 'IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5C49', '49','BR5C', 'IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5C50', '50','BR5C', 'IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5C51', '51','BR5C', 'IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5D47', '47','BR5D', 'IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5D48', '48','BR5D', 'IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5D49', '49','BR5D', 'IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5D50', '50','BR5D', 'IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5D51', '51','BR5D', 'IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5E01', '01','BR5E', 'IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5E10', '10','BR5E', 'IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5E11', '11','BR5E', 'IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5E12', '12','BR5E', 'IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5E13', '13','BR5E', 'IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5E14', '14','BR5E', 'IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5E15', '15','BR5E', 'IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5E16', '16','BR5E', 'IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5E17', '17','BR5E', 'IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5E18', '18','BR5E', 'IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5E19', '19','BR5E', 'IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5E02', '02','BR5E', 'IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5E20', '20','BR5E', 'IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5E21', '21','BR5E', 'IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5E22', '22','BR5E', 'IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5E23', '23','BR5E', 'IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5E24', '24','BR5E', 'IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5E25', '25','BR5E', 'IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5E26', '26','BR5E', 'IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5E27', '27','BR5E', 'IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5E28', '28','BR5E', 'IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5E29', '29','BR5E', 'IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5E03', '03','BR5E', 'IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5E30', '30','BR5E', 'IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5E31', '31','BR5E', 'IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5E32', '32','BR5E', 'IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5E33', '33','BR5E', 'IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5E34', '34','BR5E', 'IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5E35', '35','BR5E', 'IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5E36', '36','BR5E', 'IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5E37', '37','BR5E', 'IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5E38', '38','BR5E', 'IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5E39', '39','BR5E', 'IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5E04', '04','BR5E', 'IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5E40', '40','BR5E', 'IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5E41', '41','BR5E', 'IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5E42', '42','BR5E', 'IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5E43', '43','BR5E', 'IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5E44', '44','BR5E', 'IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5E45', '45','BR5E', 'IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5E46', '46','BR5E', 'IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5E47', '47','BR5E', 'IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5E48', '48','BR5E', 'IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5E49', '49','BR5E', 'IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5E05', '05','BR5E', 'IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5E50', '50','BR5E', 'IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5E51', '51','BR5E', 'IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5E59', '59','BR5E', 'IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5E06', '06','BR5E', 'IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5E60', '60','BR5E', 'IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5E61', '61','BR5E', 'IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5E62', '62','BR5E', 'IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5E63', '63','BR5E', 'IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5E64', '64','BR5E', 'IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5E65', '65','BR5E', 'IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5E07', '07','BR5E', 'IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5E08', '08','BR5E', 'IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5E09', '09','BR5E', 'IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5F01', '01','BR5F', 'IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5F10', '10','BR5F', 'IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5F11', '11','BR5F', 'IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5F12', '12','BR5F', 'IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5F13', '13','BR5F', 'IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5F14', '14','BR5F', 'IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5F15', '15','BR5F', 'IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5F16', '16','BR5F', 'IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5F17', '17','BR5F', 'IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5F18', '18','BR5F', 'IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5F19', '19','BR5F', 'IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5F02', '02','BR5F', 'IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5F20', '20','BR5F', 'IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5F21', '21','BR5F', 'IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5F22', '22','BR5F', 'IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5F23', '23','BR5F', 'IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5F24', '24','BR5F', 'IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5F25', '25','BR5F', 'IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5F26', '26','BR5F', 'IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5F27', '27','BR5F', 'IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5F28', '28','BR5F', 'IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5F29', '29','BR5F', 'IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5F03', '03','BR5F', 'IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5F30', '30','BR5F', 'IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5F31', '31','BR5F', 'IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5F32', '32','BR5F', 'IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5F33', '33','BR5F', 'IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5F34', '34','BR5F', 'IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5F35', '35','BR5F', 'IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5F36', '36','BR5F', 'IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5F37', '37','BR5F', 'IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5F38', '38','BR5F', 'IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5F39', '39','BR5F', 'IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5F04', '04','BR5F', 'IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5F40', '40','BR5F', 'IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5F41', '41','BR5F', 'IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5F42', '42','BR5F', 'IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5F43', '43','BR5F', 'IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5F44', '44','BR5F', 'IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5F45', '45','BR5F', 'IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5F46', '46','BR5F', 'IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5F05', '05','BR5F', 'IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5F59', '59','BR5F', 'IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5F06', '06','BR5F', 'IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5F60', '60','BR5F', 'IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5F61', '61','BR5F', 'IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5F62', '62','BR5F', 'IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5F63', '63','BR5F', 'IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5F64', '64','BR5F', 'IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5F65', '65','BR5F', 'IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5F07', '07','BR5F', 'IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5F08', '08','BR5F', 'IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5F09', '09','BR5F', 'IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5G01', '01','BR5G', 'IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5G11', '11','BR5G', 'IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5G12', '12','BR5G', 'IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5G13', '13','BR5G', 'IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5G14', '14','BR5G', 'IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5G15', '15','BR5G', 'IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5G16', '16','BR5G', 'IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5G17', '17','BR5G', 'IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5G18', '18','BR5G', 'IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5G19', '19','BR5G', 'IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5G02', '02','BR5G', 'IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5G20', '20','BR5G', 'IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5G21', '21','BR5G', 'IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5G22', '22','BR5G', 'IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5G23', '23','BR5G', 'IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5G24', '24','BR5G', 'IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5G25', '25','BR5G', 'IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5G26', '26','BR5G', 'IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5G27', '27','BR5G', 'IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5G28', '28','BR5G', 'IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5G29', '29','BR5G', 'IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5G03', '03','BR5G', 'IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5G30', '30','BR5G', 'IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5G31', '31','BR5G', 'IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5G32', '32','BR5G', 'IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5G33', '33','BR5G', 'IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5G34', '34','BR5G', 'IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5G35', '35','BR5G', 'IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5G36', '36','BR5G', 'IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5G37', '37','BR5G', 'IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5G38', '38','BR5G', 'IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5G39', '39','BR5G', 'IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5G40', '40','BR5G', 'IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5G41', '41','BR5G', 'IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5G42', '42','BR5G', 'IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5G43', '43','BR5G', 'IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5G44', '44','BR5G', 'IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5G45', '45','BR5G', 'IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5G46', '46','BR5G', 'IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5G05', '05','BR5G', 'IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5G59', '59','BR5G', 'IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5G06', '06','BR5G', 'IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5G60', '60','BR5G', 'IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5G61', '61','BR5G', 'IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5G62', '62','BR5G', 'IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5G63', '63','BR5G', 'IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5G64', '64','BR5G', 'IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5G65', '65','BR5G', 'IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5G07', '07','BR5G', 'IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5G08', '08','BR5G', 'IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5G09', '09','BR5G', 'IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5H01', '01','BR5H', 'IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5H10', '10','BR5H', 'IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5H11', '11','BR5H', 'IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5H12', '12','BR5H', 'IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5H13', '13','BR5H', 'IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5H14', '14','BR5H', 'IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5H15', '15','BR5H', 'IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5H16', '16','BR5H', 'IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5H17', '17','BR5H', 'IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5H18', '18','BR5H', 'IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5H19', '19','BR5H', 'IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5H02', '02','BR5H', 'IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5H20', '20','BR5H', 'IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5H21', '21','BR5H', 'IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5H22', '22','BR5H', 'IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5H23', '23','BR5H', 'IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5H24', '24','BR5H', 'IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5H25', '25','BR5H', 'IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5H26', '26','BR5H', 'IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5H27', '27','BR5H', 'IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5H28', '28','BR5H', 'IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5H29', '29','BR5H', 'IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5H03', '03','BR5H', 'IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5H30', '30','BR5H', 'IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5H31', '31','BR5H', 'IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5H32', '32','BR5H', 'IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5H33', '33','BR5H', 'IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5H34', '34','BR5H', 'IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5H35', '35','BR5H', 'IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5H36', '36','BR5H', 'IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5H37', '37','BR5H', 'IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5H38', '38','BR5H', 'IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5H39', '39','BR5H', 'IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5H04', '04','BR5H', 'IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5H40', '40','BR5H', 'IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5H41', '41','BR5H', 'IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5H42', '42','BR5H', 'IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5H43', '43','BR5H', 'IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5H44', '44','BR5H', 'IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5H45', '45','BR5H', 'IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5H46', '46','BR5H', 'IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5H05', '05','BR5H', 'IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5H59', '59','BR5H', 'IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5H06', '06','BR5H', 'IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5H60', '60','BR5H', 'IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5H61', '61','BR5H', 'IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5H62', '62','BR5H', 'IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5H63', '63','BR5H', 'IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5H64', '64','BR5H', 'IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5H65', '65','BR5H', 'IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5H07', '07','BR5H', 'IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5H08', '08','BR5H', 'IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5H09', '09','BR5H', 'IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5HOSPITAL', 'OSPITAL','BR5H', 'IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5K31', '31','BR5K', 'IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5LUIFD60', 'UIFD60','BR5L', 'IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5LUIFEL', 'UIFEL','BR5L', 'IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5LUIP', 'UIP','BR5L', 'IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5P18', '18','BR5P', 'IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5R35', '35','BR5R', 'IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5T25', '25','BR5T', 'IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5U57', '57','BR5U', 'IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5VL', 'L','BR5V', 'IC_SGN,IC_VMHZP'

exec MakeLocation 'BR5A01','01','BR5A','IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5A02','02','BR5A','IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5A03','03','BR5A','IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5A04','04','BR5A','IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5A05','05','BR5A','IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5A06','06','BR5A','IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5A07','07','BR5A','IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5A08','08','BR5A','IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5A09','09','BR5A','IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5A10','10','BR5A','IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5A11','11','BR5A','IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5A12','12','BR5A','IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5A13','13','BR5A','IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5A14','14','BR5A','IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5A15','15','BR5A','IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5A16','16','BR5A','IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5A17','17','BR5A','IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5A18','18','BR5A','IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5A19','19','BR5A','IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5A20','20','BR5A','IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5A21','21','BR5A','IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5A22','22','BR5A','IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5A23','23','BR5A','IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5A24','24','BR5A','IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5A25','25','BR5A','IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5A26','26','BR5A','IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5A27','27','BR5A','IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5A28','28','BR5A','IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5A29','29','BR5A','IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5A30','30','BR5A','IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5A31','31','BR5A','IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5A32','32','BR5A','IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5A33','33','BR5A','IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5A34','34','BR5A','IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5A35','35','BR5A','IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5A36','36','BR5A','IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5A37','37','BR5A','IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5A38','38','BR5A','IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5A39','39','BR5A','IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5A40','40','BR5A','IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5A41','41','BR5A','IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5A42','42','BR5A','IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5A43','43','BR5A','IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5A44','44','BR5A','IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5A45','45','BR5A','IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5A46','46','BR5A','IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5A47','47','BR5A','IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5A48','48','BR5A','IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5A49','49','BR5A','IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5A50','50','BR5A','IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5A51','51','BR5A','IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5B01','01','BR5B','IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5B02','02','BR5B','IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5B03','03','BR5B','IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5B04','04','BR5B','IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5B05','05','BR5B','IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5B06','06','BR5B','IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5B07','07','BR5B','IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5B08','08','BR5B','IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5B09','09','BR5B','IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5B10','10','BR5B','IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5B11','11','BR5B','IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5B12','12','BR5B','IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5B13','13','BR5B','IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5B14','14','BR5B','IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5B15','15','BR5B','IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5B16','16','BR5B','IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5B17','17','BR5B','IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5B18','18','BR5B','IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5B19','19','BR5B','IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5B20','20','BR5B','IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5B21','21','BR5B','IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5B22','22','BR5B','IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5B23','23','BR5B','IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5B24','24','BR5B','IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5B25','25','BR5B','IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5B26','26','BR5B','IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5B27','27','BR5B','IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5B28','28','BR5B','IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5B29','29','BR5B','IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5B30','30','BR5B','IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5B31','31','BR5B','IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5B32','32','BR5B','IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5B33','33','BR5B','IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5B34','34','BR5B','IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5B35','35','BR5B','IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5B36','36','BR5B','IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5B37','37','BR5B','IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5B38','38','BR5B','IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5B39','39','BR5B','IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5B40','40','BR5B','IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5B41','41','BR5B','IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5B42','42','BR5B','IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5B43','43','BR5B','IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5B44','44','BR5B','IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5B45','45','BR5B','IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5B46','46','BR5B','IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5B47','47','BR5B','IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5B48','48','BR5B','IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5B49','49','BR5B','IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5B50','50','BR5B','IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5B51','51','BR5B','IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5C01','01','BR5C','IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5C02','02','BR5C','IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5C03','03','BR5C','IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5C04','04','BR5C','IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5C05','05','BR5C','IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5C06','06','BR5C','IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5C07','07','BR5C','IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5C08','08','BR5C','IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5C09','09','BR5C','IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5C10','10','BR5C','IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5C11','11','BR5C','IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5C12','12','BR5C','IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5C13','13','BR5C','IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5C14','14','BR5C','IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5C15','15','BR5C','IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5C16','16','BR5C','IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5C17','17','BR5C','IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5C18','18','BR5C','IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5C19','19','BR5C','IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5C20','20','BR5C','IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5C21','21','BR5C','IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5C22','22','BR5C','IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5C23','23','BR5C','IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5C24','24','BR5C','IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5C25','25','BR5C','IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5C26','26','BR5C','IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5C27','27','BR5C','IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5C28','28','BR5C','IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5C29','29','BR5C','IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5C30','30','BR5C','IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5C31','31','BR5C','IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5C32','32','BR5C','IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5C33','33','BR5C','IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5C34','34','BR5C','IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5C35','35','BR5C','IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5C36','36','BR5C','IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5C37','37','BR5C','IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5C38','38','BR5C','IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5C39','39','BR5C','IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5C40','40','BR5C','IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5C41','41','BR5C','IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5C42','42','BR5C','IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5C43','43','BR5C','IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5C44','44','BR5C','IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5C45','45','BR5C','IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5C46','46','BR5C','IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5C47','47','BR5C','IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5C48','48','BR5C','IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5C49','49','BR5C','IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5C50','50','BR5C','IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5C51','51','BR5C','IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5D01','01','BR5D','IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5D02','02','BR5D','IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5D03','03','BR5D','IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5D04','04','BR5D','IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5D05','05','BR5D','IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5D06','06','BR5D','IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5D07','07','BR5D','IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5D08','08','BR5D','IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5D09','09','BR5D','IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5D10','10','BR5D','IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5D11','11','BR5D','IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5D12','12','BR5D','IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5D13','13','BR5D','IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5D14','14','BR5D','IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5D15','15','BR5D','IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5D16','16','BR5D','IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5D17','17','BR5D','IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5D18','18','BR5D','IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5D19','19','BR5D','IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5D20','20','BR5D','IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5D21','21','BR5D','IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5D22','22','BR5D','IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5D23','23','BR5D','IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5D24','24','BR5D','IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5D25','25','BR5D','IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5D26','26','BR5D','IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5D27','27','BR5D','IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5D28','28','BR5D','IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5D29','29','BR5D','IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5D30','30','BR5D','IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5D31','31','BR5D','IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5D32','32','BR5D','IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5D33','33','BR5D','IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5D34','34','BR5D','IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5D35','35','BR5D','IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5D36','36','BR5D','IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5D37','37','BR5D','IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5D38','38','BR5D','IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5D39','39','BR5D','IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5D40','40','BR5D','IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5D41','41','BR5D','IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5D42','42','BR5D','IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5D43','43','BR5D','IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5D44','44','BR5D','IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5D45','45','BR5D','IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5D46','46','BR5D','IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5D47','47','BR5D','IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5D48','48','BR5D','IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5D49','49','BR5D','IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5D50','50','BR5D','IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5D51','51','BR5D','IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5E01','01','BR5E','IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5E02','02','BR5E','IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5E03','03','BR5E','IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5E04','04','BR5E','IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5E05','05','BR5E','IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5E06','06','BR5E','IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5E07','07','BR5E','IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5E08','08','BR5E','IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5E09','09','BR5E','IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5E10','10','BR5E','IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5E11','11','BR5E','IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5E12','12','BR5E','IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5E13','13','BR5E','IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5E14','14','BR5E','IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5E15','15','BR5E','IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5E16','16','BR5E','IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5E17','17','BR5E','IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5E18','18','BR5E','IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5E19','19','BR5E','IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5E20','20','BR5E','IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5E21','21','BR5E','IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5E22','22','BR5E','IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5E23','23','BR5E','IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5E24','24','BR5E','IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5E25','25','BR5E','IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5E26','26','BR5E','IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5E27','27','BR5E','IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5E28','28','BR5E','IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5E29','29','BR5E','IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5E30','30','BR5E','IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5E31','31','BR5E','IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5E32','32','BR5E','IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5E33','33','BR5E','IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5E34','34','BR5E','IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5E35','35','BR5E','IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5E36','36','BR5E','IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5E37','37','BR5E','IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5E38','38','BR5E','IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5E39','39','BR5E','IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5E40','40','BR5E','IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5E41','41','BR5E','IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5E42','42','BR5E','IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5E43','43','BR5E','IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5E44','44','BR5E','IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5E45','45','BR5E','IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5E46','46','BR5E','IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5E47','47','BR5E','IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5E48','48','BR5E','IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5E49','49','BR5E','IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5E50','50','BR5E','IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5E51','51','BR5E','IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5E59','59','BR5E','IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5E60','60','BR5E','IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5E61','61','BR5E','IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5E62','62','BR5E','IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5E63','63','BR5E','IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5E64','64','BR5E','IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5E65','65','BR5E','IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5F01','01','BR5F','IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5F02','02','BR5F','IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5F03','03','BR5F','IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5F04','04','BR5F','IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5F05','05','BR5F','IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5F06','06','BR5F','IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5F07','07','BR5F','IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5F08','08','BR5F','IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5F09','09','BR5F','IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5F10','10','BR5F','IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5F11','11','BR5F','IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5F12','12','BR5F','IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5F13','13','BR5F','IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5F14','14','BR5F','IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5F15','15','BR5F','IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5F16','16','BR5F','IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5F17','17','BR5F','IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5F18','18','BR5F','IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5F19','19','BR5F','IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5F20','20','BR5F','IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5F21','21','BR5F','IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5F22','22','BR5F','IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5F23','23','BR5F','IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5F24','24','BR5F','IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5F25','25','BR5F','IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5F26','26','BR5F','IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5F27','27','BR5F','IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5F28','28','BR5F','IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5F29','29','BR5F','IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5F30','30','BR5F','IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5F31','31','BR5F','IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5F32','32','BR5F','IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5F33','33','BR5F','IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5F34','34','BR5F','IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5F35','35','BR5F','IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5F36','36','BR5F','IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5F37','37','BR5F','IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5F38','38','BR5F','IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5F39','39','BR5F','IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5F40','40','BR5F','IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5F41','41','BR5F','IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5F42','42','BR5F','IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5F43','43','BR5F','IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5F44','44','BR5F','IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5F45','45','BR5F','IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5F46','46','BR5F','IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5F59','59','BR5F','IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5F60','60','BR5F','IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5F61','61','BR5F','IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5F62','62','BR5F','IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5F63','63','BR5F','IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5F64','64','BR5F','IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5F65','65','BR5F','IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5F01','01','BR5F','IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5F02','02','BR5F','IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5F03','03','BR5F','IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5F04','04','BR5F','IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5F05','05','BR5F','IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5F06','06','BR5F','IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5F07','07','BR5F','IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5F08','08','BR5F','IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5F09','09','BR5F','IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5F10','10','BR5F','IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5F11','11','BR5F','IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5F12','12','BR5F','IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5F13','13','BR5F','IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5F14','14','BR5F','IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5F15','15','BR5F','IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5F16','16','BR5F','IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5F17','17','BR5F','IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5F18','18','BR5F','IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5F19','19','BR5F','IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5F20','20','BR5F','IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5F21','21','BR5F','IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5F22','22','BR5F','IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5F23','23','BR5F','IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5F24','24','BR5F','IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5F25','25','BR5F','IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5F26','26','BR5F','IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5F27','27','BR5F','IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5F28','28','BR5F','IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5F29','29','BR5F','IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5F30','30','BR5F','IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5F31','31','BR5F','IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5F32','32','BR5F','IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5F33','33','BR5F','IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5F34','34','BR5F','IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5F35','35','BR5F','IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5F36','36','BR5F','IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5F37','37','BR5F','IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5F38','38','BR5F','IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5F39','39','BR5F','IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5F40','40','BR5F','IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5F41','41','BR5F','IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5F42','42','BR5F','IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5F43','43','BR5F','IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5F44','44','BR5F','IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5F45','45','BR5F','IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5F46','46','BR5F','IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5F59','59','BR5F','IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5F60','60','BR5F','IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5F61','61','BR5F','IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5F62','62','BR5F','IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5F63','63','BR5F','IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5F64','64','BR5F','IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5F65','65','BR5F','IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5F01','01','BR5F','IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5F02','02','BR5F','IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5F03','03','BR5F','IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5F04','04','BR5F','IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5F05','05','BR5F','IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5F06','06','BR5F','IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5F07','07','BR5F','IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5F08','08','BR5F','IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5F09','09','BR5F','IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5F10','10','BR5F','IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5F11','11','BR5F','IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5F12','12','BR5F','IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5F13','13','BR5F','IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5F14','14','BR5F','IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5F15','15','BR5F','IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5F16','16','BR5F','IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5F17','17','BR5F','IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5F18','18','BR5F','IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5F19','19','BR5F','IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5F20','20','BR5F','IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5F21','21','BR5F','IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5F22','22','BR5F','IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5F23','23','BR5F','IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5F24','24','BR5F','IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5F25','25','BR5F','IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5F26','26','BR5F','IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5F27','27','BR5F','IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5F28','28','BR5F','IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5F29','29','BR5F','IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5F30','30','BR5F','IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5F31','31','BR5F','IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5F32','32','BR5F','IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5F33','33','BR5F','IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5F34','34','BR5F','IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5F35','35','BR5F','IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5F36','36','BR5F','IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5F37','37','BR5F','IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5F38','38','BR5F','IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5F39','39','BR5F','IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5F40','40','BR5F','IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5F41','41','BR5F','IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5F42','42','BR5F','IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5F43','43','BR5F','IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5F44','44','BR5F','IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5F45','45','BR5F','IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5F46','46','BR5F','IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5F59','59','BR5F','IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5F60','60','BR5F','IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5F61','61','BR5F','IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5F62','62','BR5F','IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5F63','63','BR5F','IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5F64','64','BR5F','IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5F65','65','BR5F','IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5G01','01','BR5G','IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5G02','02','BR5G','IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5G03','03','BR5G','IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5G04','04','BR5G','IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5G05','05','BR5G','IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5G06','06','BR5G','IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5G07','07','BR5G','IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5G08','08','BR5G','IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5G09','09','BR5G','IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5G10','10','BR5G','IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5G11','11','BR5G','IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5G12','12','BR5G','IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5G13','13','BR5G','IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5G14','14','BR5G','IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5G15','15','BR5G','IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5G16','16','BR5G','IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5G17','17','BR5G','IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5G18','18','BR5G','IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5G19','19','BR5G','IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5G20','20','BR5G','IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5G21','21','BR5G','IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5G22','22','BR5G','IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5G23','23','BR5G','IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5G24','24','BR5G','IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5G25','25','BR5G','IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5G26','26','BR5G','IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5G27','27','BR5G','IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5G28','28','BR5G','IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5G29','29','BR5G','IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5G30','30','BR5G','IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5G31','31','BR5G','IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5G32','32','BR5G','IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5G33','33','BR5G','IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5G34','34','BR5G','IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5G35','35','BR5G','IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5G36','36','BR5G','IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5G37','37','BR5G','IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5G38','38','BR5G','IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5G39','39','BR5G','IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5G40','40','BR5G','IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5G41','41','BR5G','IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5G42','42','BR5G','IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5G43','43','BR5G','IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5G44','44','BR5G','IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5G45','45','BR5G','IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5G46','46','BR5G','IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5G59','59','BR5G','IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5G60','60','BR5G','IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5G61','61','BR5G','IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5G62','62','BR5G','IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5G63','63','BR5G','IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5G64','64','BR5G','IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5G65','65','BR5G','IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5H01','01','BR5H','IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5H02','02','BR5H','IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5H03','03','BR5H','IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5H04','04','BR5H','IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5H05','05','BR5H','IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5H06','06','BR5H','IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5H07','07','BR5H','IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5H08','08','BR5H','IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5H09','09','BR5H','IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5H10','10','BR5H','IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5H11','11','BR5H','IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5H12','12','BR5H','IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5H13','13','BR5H','IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5H14','14','BR5H','IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5H15','15','BR5H','IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5H16','16','BR5H','IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5H17','17','BR5H','IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5H18','18','BR5H','IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5H19','19','BR5H','IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5H20','20','BR5H','IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5H21','21','BR5H','IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5H22','22','BR5H','IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5H23','23','BR5H','IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5H24','24','BR5H','IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5H25','25','BR5H','IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5H26','26','BR5H','IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5H27','27','BR5H','IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5H28','28','BR5H','IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5H29','29','BR5H','IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5H30','30','BR5H','IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5H31','31','BR5H','IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5H32','32','BR5H','IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5H33','33','BR5H','IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5H34','34','BR5H','IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5H35','35','BR5H','IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5H36','36','BR5H','IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5H37','37','BR5H','IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5H38','38','BR5H','IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5H39','39','BR5H','IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5H40','40','BR5H','IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5H41','41','BR5H','IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5H42','42','BR5H','IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5H43','43','BR5H','IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5H44','44','BR5H','IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5H45','45','BR5H','IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5H46','46','BR5H','IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5H59','59','BR5H','IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5H60','60','BR5H','IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5H61','61','BR5H','IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5H62','62','BR5H','IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5H63','63','BR5H','IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5H64','64','BR5H','IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5H65','65','BR5H','IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5K31','31','BR5K','IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5LUIFD60','UIFD60','BR5L','IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5LUIFEL','UIFEL','BR5L','IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5LUIP','UIP','BR5L','IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5P18','18','BR5P','IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5R35','35','BR5R','IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5T25','25','BR5T','IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5U57','57','BR5U','IC_SGN,IC_VMHZP'
exec MakeLocation 'BR5VL','L','BR5V','IC_SGN,IC_VMHZP'

update LOCATION set DESCRIPTION = 'Zone U' where ADDRESS = 'BR5U'
update LOCATION set DESCRIPTION = 'Zone V' where ADDRESS = 'BR5V'

set nocount off
drop proc [dbo].[MakeLocation]

--delete lic from LOCATION_INTERNAL_COMPANY lic, LOCATION l where lic.LOCATION_ID = l.LOCATION_ID and l.CREATE_USER = 'sys170110'
--delete from LOCATION where CREATE_USER = 'sys170110'
